package com.smi.travel.datalayer.entity;
// Generated Jul 24, 2015 11:07:37 AM by Hibernate Tools 3.6.0



/**
 * AccountCode generated by hbm2java
 */
public class AccountCode {


     private String id;
     private String accCode;
     private String detail;
     private String accType;

    public AccountCode() {
    }

    public AccountCode(String accCode, String detail, String accType) {
       this.accCode = accCode;
       this.detail = detail;
       this.accType = accType;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getAccCode() {
        return this.accCode;
    }
    
    public void setAccCode(String accCode) {
        this.accCode = accCode;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public String getAccType() {
        return this.accType;
    }
    
    public void setAccType(String accType) {
        this.accType = accType;
    }




}


