package com.smi.travel.datalayer.entity;
// Generated Oct 7, 2015 9:59:53 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdvanceReceive generated by hbm2java
 */
public class AdvanceReceive  {


     private String  id;
     private MAccpay MAccpay;
     private String recTo;
     private Date recDate;
     private String recName;
     private String arCode;
     private String description;
     private BigDecimal cashAmount;
     private BigDecimal bankAmount;
     private BigDecimal chqAmount;
     private String chqBank;
     private Date chqDate;
     private String chqNo;
     private String createBy;
     private Date createDate;
     private BigDecimal recAmount;
     private String vatType;
     private Set advanceReceiveCredits = new HashSet(0);

    public AdvanceReceive() {
    }

    public AdvanceReceive(MAccpay MAccpay, String recTo, Date recDate, String recName, String arCode, String description, BigDecimal cashAmount, BigDecimal bankAmount, BigDecimal chqAmount, String chqBank, Date chqDate, String chqNo, String createBy, Date createDate, BigDecimal recAmount, String vatType, Set advanceReceiveCredits) {
       this.MAccpay = MAccpay;
       this.recTo = recTo;
       this.recDate = recDate;
       this.recName = recName;
       this.arCode = arCode;
       this.description = description;
       this.cashAmount = cashAmount;
       this.bankAmount = bankAmount;
       this.chqAmount = chqAmount;
       this.chqBank = chqBank;
       this.chqDate = chqDate;
       this.chqNo = chqNo;
       this.createBy = createBy;
       this.createDate = createDate;
       this.recAmount = recAmount;
       this.vatType = vatType;
       this.advanceReceiveCredits = advanceReceiveCredits;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public MAccpay getMAccpay() {
        return this.MAccpay;
    }
    
    public void setMAccpay(MAccpay MAccpay) {
        this.MAccpay = MAccpay;
    }
    public String getRecTo() {
        return this.recTo;
    }
    
    public void setRecTo(String recTo) {
        this.recTo = recTo;
    }
    public Date getRecDate() {
        return this.recDate;
    }
    
    public void setRecDate(Date recDate) {
        this.recDate = recDate;
    }
    public String getRecName() {
        return this.recName;
    }
    
    public void setRecName(String recName) {
        this.recName = recName;
    }
    public String getArCode() {
        return this.arCode;
    }
    
    public void setArCode(String arCode) {
        this.arCode = arCode;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getCashAmount() {
        return this.cashAmount;
    }
    
    public void setCashAmount(BigDecimal cashAmount) {
        this.cashAmount = cashAmount;
    }
    public BigDecimal getBankAmount() {
        return this.bankAmount;
    }
    
    public void setBankAmount(BigDecimal bankAmount) {
        this.bankAmount = bankAmount;
    }
    public BigDecimal getChqAmount() {
        return this.chqAmount;
    }
    
    public void setChqAmount(BigDecimal chqAmount) {
        this.chqAmount = chqAmount;
    }
    public String getChqBank() {
        return this.chqBank;
    }
    
    public void setChqBank(String chqBank) {
        this.chqBank = chqBank;
    }
    public Date getChqDate() {
        return this.chqDate;
    }
    
    public void setChqDate(Date chqDate) {
        this.chqDate = chqDate;
    }
    public String getChqNo() {
        return this.chqNo;
    }
    
    public void setChqNo(String chqNo) {
        this.chqNo = chqNo;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public BigDecimal getRecAmount() {
        return this.recAmount;
    }
    
    public void setRecAmount(BigDecimal recAmount) {
        this.recAmount = recAmount;
    }
    public String getVatType() {
        return this.vatType;
    }
    
    public void setVatType(String vatType) {
        this.vatType = vatType;
    }
    public Set getAdvanceReceiveCredits() {
        return this.advanceReceiveCredits;
    }
    
    public void setAdvanceReceiveCredits(Set advanceReceiveCredits) {
        this.advanceReceiveCredits = advanceReceiveCredits;
    }




}


