package com.smi.travel.datalayer.entity;
// Generated Oct 7, 2015 9:59:53 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * AdvanceReceiveCredit generated by hbm2java
 */
public class AdvanceReceiveCredit  implements java.io.Serializable {


     private String id;
     private AdvanceReceive advanceReceive;
     private MCreditBank MCreditBank;
     private String creditNo;
     private Date creditExpire;
     private BigDecimal creditAmount;

    public AdvanceReceiveCredit() {
    }

    public AdvanceReceiveCredit(AdvanceReceive advanceReceive, MCreditBank MCreditBank, String creditNo, Date creditExpire, BigDecimal creditAmount) {
       this.advanceReceive = advanceReceive;
       this.MCreditBank = MCreditBank;
       this.creditNo = creditNo;
       this.creditExpire = creditExpire;
       this.creditAmount = creditAmount;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public AdvanceReceive getAdvanceReceive() {
        return this.advanceReceive;
    }
    
    public void setAdvanceReceive(AdvanceReceive advanceReceive) {
        this.advanceReceive = advanceReceive;
    }
    public MCreditBank getMCreditBank() {
        return this.MCreditBank;
    }
    
    public void setMCreditBank(MCreditBank MCreditBank) {
        this.MCreditBank = MCreditBank;
    }
    public String getCreditNo() {
        return this.creditNo;
    }
    
    public void setCreditNo(String creditNo) {
        this.creditNo = creditNo;
    }
    public Date getCreditExpire() {
        return this.creditExpire;
    }
    
    public void setCreditExpire(Date creditExpire) {
        this.creditExpire = creditExpire;
    }
    public BigDecimal getCreditAmount() {
        return this.creditAmount;
    }
    
    public void setCreditAmount(BigDecimal creditAmount) {
        this.creditAmount = creditAmount;
    }




}


