package com.smi.travel.datalayer.entity;
// Generated Nov 4, 2015 10:49:34 AM by Hibernate Tools 4.3.1



/**
 * AirticketRefund generated by hbm2java
 */
public class AirticketRefund  implements java.io.Serializable {
     private Integer id;
     private AirticketBooking airticketBooking;
     private RefundAirticket refundAirticket;

    public AirticketRefund() {
    }

    public AirticketRefund(AirticketBooking airticketBooking, RefundAirticket refundAirticket) {
       this.airticketBooking = airticketBooking;
       this.refundAirticket = refundAirticket;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public AirticketBooking getAirticketBooking() {
        return this.airticketBooking;
    }
    
    public void setAirticketBooking(AirticketBooking airticketBooking) {
        this.airticketBooking = airticketBooking;
    }
    public RefundAirticket getRefundAirticket() {
        return this.refundAirticket;
    }
    
    public void setRefundAirticket(RefundAirticket refundAirticket) {
        this.refundAirticket = refundAirticket;
    }




}


