package com.smi.travel.datalayer.entity;
// Generated Dec 22, 2014 5:59:06 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * AirticketFlight generated by hbm2java
 */
public class AirticketFlight {

     private String id;
     private MTicketType MTicketType;
     private AirticketAirline airticketAirline;
     private MFlight MFlight;
     private MItemstatus MItemstatus;
     private String flightNo;
     private String sourceCode;
     private String desCode;
     private Date departDate;
     private Date arriveDate;
     private String departTime;
     private String arriveTime;
     private String isBill;
     private Integer adCost;
     private Integer adPrice;
     private Integer adTax;
     private Integer chCost;
     private Integer chPrice;
     private Integer chTax;
     private Integer inCost;
     private Integer inPrice;
     private Integer inTax;
     private Integer costRefund;
     private Integer TotalPrice;
     private Integer TotalCost;
     private String subFlightClass;
     private Integer flightOrder;

    public AirticketFlight() {
    }

	
    public AirticketFlight(String flightNo, String sourceCode, String desCode, Date departDate, Date arriveDate, String departTime, String arriveTime) {
        this.flightNo = flightNo;
        this.sourceCode = sourceCode;
        this.desCode = desCode;
        this.departDate = departDate;
        this.arriveDate = arriveDate;
        this.departTime = departTime;
        this.arriveTime = arriveTime;
        
    }
    public AirticketFlight(MTicketType MTicketType, AirticketAirline airticketAirline, MFlight MFlight, MItemstatus MItemstatus, String flightNo, String sourceCode, String desCode, Date departDate, Date arriveDate, String departTime, String arriveTime, String isBill, Integer adCost, Integer adPrice, Integer adTax, Integer chCost, Integer chPrice, Integer chTax, Integer inCost, Integer inPrice, Integer inTax, Integer costRefund,Integer TotalPrice,Integer TotalCost,String subFlightClass, Integer flightOrder) {
       this.MTicketType = MTicketType;
       this.airticketAirline = airticketAirline;
       this.MFlight = MFlight;
       this.MItemstatus = MItemstatus;
       this.flightNo = flightNo;
        this.sourceCode = sourceCode;
        this.desCode = desCode;
       this.departDate = departDate;
       this.arriveDate = arriveDate;
       this.departTime = departTime;
       this.arriveTime = arriveTime;
       this.isBill = isBill;
       this.adCost = adCost;
       this.adPrice = adPrice;
       this.adTax = adTax;
       this.chCost = chCost;
       this.chPrice = chPrice;
       this.chTax = chTax;
       this.inCost = inCost;
       this.inPrice = inPrice;
       this.inTax = inTax;
       this.costRefund = costRefund;
       this.TotalPrice = TotalPrice;
       this.TotalCost = TotalCost;
       this.subFlightClass = subFlightClass;
       this.flightOrder = flightOrder;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public MTicketType getMTicketType() {
        return this.MTicketType;
    }
    
    public void setMTicketType(MTicketType MTicketType) {
        this.MTicketType = MTicketType;
    }
    public AirticketAirline getAirticketAirline() {
        return this.airticketAirline;
    }
    
    public void setAirticketAirline(AirticketAirline airticketAirline) {
        this.airticketAirline = airticketAirline;
    }
    public MFlight getMFlight() {
        return this.MFlight;
    }
    
    public void setMFlight(MFlight MFlight) {
        this.MFlight = MFlight;
    }
    public MItemstatus getMItemstatus() {
        return this.MItemstatus;
    }
    
    public void setMItemstatus(MItemstatus MItemstatus) {
        this.MItemstatus = MItemstatus;
    }
    public String getFlightNo() {
        return this.flightNo;
    }
    
    public void setFlightNo(String flightNo) {
        this.flightNo = flightNo;
    }

    public String getSourceCode() {
        return sourceCode;
    }

    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode;
    }

    public String getDesCode() {
        return desCode;
    }

    public void setDesCode(String desCode) {
        this.desCode = desCode;
    }

    
    public Date getDepartDate() {
        return this.departDate;
    }
    
    public void setDepartDate(Date departDate) {
        this.departDate = departDate;
    }
    public Date getArriveDate() {
        return this.arriveDate;
    }
    
    public void setArriveDate(Date arriveDate) {
        this.arriveDate = arriveDate;
    }
    public String getDepartTime() {
        return this.departTime;
    }
    
    public void setDepartTime(String departTime) {
        this.departTime = departTime;
    }
    public String getArriveTime() {
        return this.arriveTime;
    }
    
    public void setArriveTime(String arriveTime) {
        this.arriveTime = arriveTime;
    }
    public String getIsBill() {
        return this.isBill;
    }
    
    public void setIsBill(String isBill) {
        this.isBill = isBill;
    }
    public Integer getAdCost() {
        return this.adCost;
    }
    
    public void setAdCost(Integer adCost) {
        this.adCost = adCost;
    }
    public Integer getAdPrice() {
        return this.adPrice;
    }
    
    public void setAdPrice(Integer adPrice) {
        this.adPrice = adPrice;
    }
    public Integer getAdTax() {
        return this.adTax;
    }
    
    public void setAdTax(Integer adTax) {
        this.adTax = adTax;
    }
    public Integer getChCost() {
        return this.chCost;
    }
    
    public void setChCost(Integer chCost) {
        this.chCost = chCost;
    }
    public Integer getChPrice() {
        return this.chPrice;
    }
    
    public void setChPrice(Integer chPrice) {
        this.chPrice = chPrice;
    }
    public Integer getChTax() {
        return this.chTax;
    }
    
    public void setChTax(Integer chTax) {
        this.chTax = chTax;
    }
    public Integer getInCost() {
        return this.inCost;
    }
    
    public void setInCost(Integer inCost) {
        this.inCost = inCost;
    }
    public Integer getInPrice() {
        return this.inPrice;
    }
    
    public void setInPrice(Integer inPrice) {
        this.inPrice = inPrice;
    }
    public Integer getInTax() {
        return this.inTax;
    }
    
    public void setInTax(Integer inTax) {
        this.inTax = inTax;
    }
    public Integer getCostRefund() {
        return this.costRefund;
    }
    
    public void setCostRefund(Integer costRefund) {
        this.costRefund = costRefund;
    }

    public Integer getTotalPrice() {
        return TotalPrice;
    }

    public void setTotalPrice(Integer TotalPrice) {
        this.TotalPrice = TotalPrice;
    }

    public Integer getTotalCost() {
        return TotalCost;
    }

    public void setTotalCost(Integer TotalCost) {
        this.TotalCost = TotalCost;
    }

    public String getSubFlightClass() {
        return subFlightClass;
    }

    public void setSubFlightClass(String subFlightClass) {
        this.subFlightClass = subFlightClass;
    }

    public Integer getFlightOrder() {
        return flightOrder;
    }

    public void setFlightOrder(Integer flightOrder) {
        this.flightOrder = flightOrder;
    }
 
}


