package com.smi.travel.datalayer.entity;
// Generated Dec 22, 2014 5:59:06 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;




/**
 * AirticketDesc generated by hbm2java
 */
public class AirticketDesc   {


     private String id;
     private AirticketBooking airticketBooking; 
     private String detail;
     private BigDecimal cost;
     private Integer qty;
     private BigDecimal amount;
     private Integer isBill;
     private String curAmount;
     private String curCost;

    public AirticketDesc() {
    }

	
    public AirticketDesc(AirticketBooking airticketBooking, String detail) {
        this.airticketBooking = airticketBooking;
        this.detail = detail;
    }
    public AirticketDesc(AirticketBooking airticketBooking, String detail, BigDecimal cost, Integer qty, BigDecimal amount,Integer isBill ,String curAmount,String curCost) {
       this.airticketBooking = airticketBooking;
       this.detail = detail;
       this.cost = cost;
       this.qty = qty;
       this.amount = amount;
       this.isBill = isBill;
       this.curAmount = curAmount;
       this.curCost = curCost;
       
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public AirticketBooking getAirticketBooking() {
        return airticketBooking;
    }

    public void setAirticketBooking(AirticketBooking airticketBooking) {
        this.airticketBooking = airticketBooking;
    }
    
    
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }

    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    public Integer getIsBill() {
        return isBill;
    }

    public void setIsBill(Integer isBill) {
        this.isBill = isBill;
    }

    public String getCurAmount() {
        return curAmount;
    }

    public void setCurAmount(String curAmount) {
        this.curAmount = curAmount;
    }

    public String getCurCost() {
        return curCost;
    }

    public void setCurCost(String curCost) {
        this.curCost = curCost;
    }

    public BigDecimal getCost() {
        return cost;
    }

    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
   
}


