package com.smi.travel.datalayer.entity;
// Generated Dec 22, 2014 5:59:06 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * AirticketAirline generated by hbm2java
 */
public class AirticketAirline   {


     private String id;
     private MAirline MAirline;
     private AirticketPnr airticketPnr;
     private Date ticketDate;
     private Set airticketFlights = new LinkedHashSet(0);
     private Set airticketPassengers = new LinkedHashSet(0);

   public AirticketAirline() {
    }

	
    public AirticketAirline(AirticketPnr airticketPnr, Date ticketDate) {
        this.airticketPnr = airticketPnr;
        this.ticketDate = ticketDate;
    }
    public AirticketAirline(MAirline MAirline, AirticketPnr airticketPnr, Date ticketDate, Set airticketFlights, Set airticketPassengers) {
       this.MAirline = MAirline;
       this.airticketPnr = airticketPnr;
       this.ticketDate = ticketDate;
       this.airticketFlights = airticketFlights;
       this.airticketPassengers = airticketPassengers;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public MAirline getMAirline() {
        return this.MAirline;
    }
    
    public void setMAirline(MAirline MAirline) {
        this.MAirline = MAirline;
    }
    public AirticketPnr getAirticketPnr() {
        return this.airticketPnr;
    }
    
    public void setAirticketPnr(AirticketPnr airticketPnr) {
        this.airticketPnr = airticketPnr;
    }
    public Date getTicketDate() {
        return this.ticketDate;
    }
    
    public void setTicketDate(Date ticketDate) {
        this.ticketDate = ticketDate;
    }
    public Set getAirticketFlights() {
        return this.airticketFlights;
    }
    
    public void setAirticketFlights(Set airticketFlights) {
        this.airticketFlights = airticketFlights;
    }
    public Set getAirticketPassengers() {
        return this.airticketPassengers;
    }
    
    public void setAirticketPassengers(Set airticketPassengers) {
        this.airticketPassengers = airticketPassengers;
    }


}


