package com.smi.travel.datalayer.entity;
// Generated Dec 22, 2014 5:59:06 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * AirticketFlight generated by hbm2java
 */
public class AirticketFlight {

     private String id;
     private MTicketType MTicketType;
     private AirticketAirline airticketAirline;
     private MFlight MFlight;
     private MItemstatus MItemstatus;
     private String flightNo;
     private String sourceCode;
     private String desCode;
     private Date departDate;
     private Date arriveDate;
     private String departTime;
     private String arriveTime;
     private String isBill;
     private BigDecimal TotalPrice;
     private BigDecimal TotalCost;
     private BigDecimal adCost;
     private BigDecimal adPrice;
     private BigDecimal adTax;
     private BigDecimal chCost;
     private BigDecimal chPrice;
     private BigDecimal chTax;
     private BigDecimal inCost;
     private BigDecimal inPrice;
     private BigDecimal inTax;
     private BigDecimal costRefund;
     private String subFlightClass;
     private Integer flightOrder;
     private BigDecimal adTaxCost;
     private BigDecimal chTaxCost;
     private BigDecimal inTaxCost;
     
    public AirticketFlight() {
    }

	
    public AirticketFlight(String flightNo, String sourceCode, String desCode, Date departDate, Date arriveDate, String departTime, String arriveTime) {
        this.flightNo = flightNo;
        this.sourceCode = sourceCode;
        this.desCode = desCode;
        this.departDate = departDate;
        this.arriveDate = arriveDate;
        this.departTime = departTime;
        this.arriveTime = arriveTime;
        
    }
    public AirticketFlight(MTicketType MTicketType, AirticketAirline airticketAirline, MFlight MFlight, MItemstatus MItemstatus, String flightNo, String sourceCode, String desCode, Date departDate, Date arriveDate, String departTime, String arriveTime, String isBill, BigDecimal adCost, BigDecimal adPrice, BigDecimal adTax, BigDecimal chCost, BigDecimal chPrice, BigDecimal chTax, BigDecimal inCost, BigDecimal inPrice, BigDecimal inTax, BigDecimal costRefund,BigDecimal TotalPrice,BigDecimal TotalCost,String subFlightClass, Integer flightOrder) {
       this.MTicketType = MTicketType;
       this.airticketAirline = airticketAirline;
       this.MFlight = MFlight;
       this.MItemstatus = MItemstatus;
       this.flightNo = flightNo;
        this.sourceCode = sourceCode;
        this.desCode = desCode;
       this.departDate = departDate;
       this.arriveDate = arriveDate;
       this.departTime = departTime;
       this.arriveTime = arriveTime;
       this.isBill = isBill;
       this.adCost = adCost;
       this.adPrice = adPrice;
       this.adTax = adTax;
       this.chCost = chCost;
       this.chPrice = chPrice;
       this.chTax = chTax;
       this.inCost = inCost;
       this.inPrice = inPrice;
       this.inTax = inTax;
       this.costRefund = costRefund;
       this.TotalPrice = TotalPrice;
       this.TotalCost = TotalCost;
       this.subFlightClass = subFlightClass;
       this.flightOrder = flightOrder;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public MTicketType getMTicketType() {
        return this.MTicketType;
    }
    
    public void setMTicketType(MTicketType MTicketType) {
        this.MTicketType = MTicketType;
    }
    public AirticketAirline getAirticketAirline() {
        return this.airticketAirline;
    }
    
    public void setAirticketAirline(AirticketAirline airticketAirline) {
        this.airticketAirline = airticketAirline;
    }
    public MFlight getMFlight() {
        return this.MFlight;
    }
    
    public void setMFlight(MFlight MFlight) {
        this.MFlight = MFlight;
    }
    public MItemstatus getMItemstatus() {
        return this.MItemstatus;
    }
    
    public void setMItemstatus(MItemstatus MItemstatus) {
        this.MItemstatus = MItemstatus;
    }
    public String getFlightNo() {
        return this.flightNo;
    }
    
    public void setFlightNo(String flightNo) {
        this.flightNo = flightNo;
    }

    public String getSourceCode() {
        return sourceCode;
    }

    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode;
    }

    public String getDesCode() {
        return desCode;
    }

    public void setDesCode(String desCode) {
        this.desCode = desCode;
    }

    
    public Date getDepartDate() {
        return this.departDate;
    }
    
    public void setDepartDate(Date departDate) {
        this.departDate = departDate;
    }
    public Date getArriveDate() {
        return this.arriveDate;
    }
    
    public void setArriveDate(Date arriveDate) {
        this.arriveDate = arriveDate;
    }
    public String getDepartTime() {
        return this.departTime;
    }
    
    public void setDepartTime(String departTime) {
        this.departTime = departTime;
    }
    public String getArriveTime() {
        return this.arriveTime;
    }
    
    public void setArriveTime(String arriveTime) {
        this.arriveTime = arriveTime;
    }
    public String getIsBill() {
        return this.isBill;
    }
    
    public void setIsBill(String isBill) {
        this.isBill = isBill;
    }

    public BigDecimal getTotalPrice() {
        return TotalPrice;
    }

    public void setTotalPrice(BigDecimal TotalPrice) {
        this.TotalPrice = TotalPrice;
    }

    public BigDecimal getTotalCost() {
        return TotalCost;
    }

    public void setTotalCost(BigDecimal TotalCost) {
        this.TotalCost = TotalCost;
    }

    public BigDecimal getAdCost() {
        return adCost;
    }

    public void setAdCost(BigDecimal adCost) {
        this.adCost = adCost;
    }

    public BigDecimal getAdPrice() {
        return adPrice;
    }

    public void setAdPrice(BigDecimal adPrice) {
        this.adPrice = adPrice;
    }

    public BigDecimal getAdTax() {
        return adTax;
    }

    public void setAdTax(BigDecimal adTax) {
        this.adTax = adTax;
    }

    public BigDecimal getChCost() {
        return chCost;
    }

    public void setChCost(BigDecimal chCost) {
        this.chCost = chCost;
    }

    public BigDecimal getChPrice() {
        return chPrice;
    }

    public void setChPrice(BigDecimal chPrice) {
        this.chPrice = chPrice;
    }

    public BigDecimal getChTax() {
        return chTax;
    }

    public void setChTax(BigDecimal chTax) {
        this.chTax = chTax;
    }

    public BigDecimal getInCost() {
        return inCost;
    }

    public void setInCost(BigDecimal inCost) {
        this.inCost = inCost;
    }

    public BigDecimal getInPrice() {
        return inPrice;
    }

    public void setInPrice(BigDecimal inPrice) {
        this.inPrice = inPrice;
    }

    public BigDecimal getInTax() {
        return inTax;
    }

    public void setInTax(BigDecimal inTax) {
        this.inTax = inTax;
    }

    public BigDecimal getCostRefund() {
        return costRefund;
    }

    public void setCostRefund(BigDecimal costRefund) {
        this.costRefund = costRefund;
    }

    public String getSubFlightClass() {
        return subFlightClass;
    }

    public void setSubFlightClass(String subFlightClass) {
        this.subFlightClass = subFlightClass;
    }

    public Integer getFlightOrder() {
        return flightOrder;
    }

    public void setFlightOrder(Integer flightOrder) {
        this.flightOrder = flightOrder;
    }

    public BigDecimal getAdTaxCost() {
        return adTaxCost;
    }

    public void setAdTaxCost(BigDecimal adTaxCost) {
        this.adTaxCost = adTaxCost;
    }

    public BigDecimal getChTaxCost() {
        return chTaxCost;
    }

    public void setChTaxCost(BigDecimal chTaxCost) {
        this.chTaxCost = chTaxCost;
    }

    public BigDecimal getInTaxCost() {
        return inTaxCost;
    }

    public void setInTaxCost(BigDecimal inTaxCost) {
        this.inTaxCost = inTaxCost;
    }
   
 
}


