package com.smi.travel.datalayer.entity;
// Generated Dec 24, 2014 10:24:56 AM by Hibernate Tools 3.6.0

import java.util.Date;




/**
 * BillableDesc generated by hbm2java
 */
public class BillableDesc  {


     private String id;
     private Billable billable;
     private MBilltype MBilltype;
     private AirticketAirline airticketAirline;
     private int cost;
     private int price;
     private int isBill;
     private String remark;
     private String detail;
     private String currency;
     private String curCost;
     private String refItemId;
     private Date billDate;

     
    public BillableDesc() {
    }

	
    public BillableDesc(Billable billable, int cost, int price, int isBill) {
        this.billable = billable;
        this.cost = cost;
        this.price = price;
        this.isBill = isBill;
    }
    public BillableDesc(Billable billable, MBilltype MBilltype, AirticketAirline airticketAirline, int cost, int price, int isBill, String remark,String detail,String currency,Date billDate,String refItemId,String curCost) {
       this.billable = billable;
       this.MBilltype = MBilltype;
       this.airticketAirline = airticketAirline;
       this.cost = cost;
       this.price = price;
       this.isBill = isBill;
       this.remark = remark;
       this.detail = detail;
       this.currency = currency;
       this.curCost = curCost;
       this.billDate = billDate;
       this.refItemId = refItemId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Billable getBillable() {
        return this.billable;
    }
    
    public void setBillable(Billable billable) {
        this.billable = billable;
    }
    public MBilltype getMBilltype() {
        return this.MBilltype;
    }
    
    public void setMBilltype(MBilltype MBilltype) {
        this.MBilltype = MBilltype;
    }
    public AirticketAirline getAirticketAirline() {
        return this.airticketAirline;
    }
    
    public void setAirticketAirline(AirticketAirline airticketAirline) {
        this.airticketAirline = airticketAirline;
    }
    public int getCost() {
        return this.cost;
    }
    
    public void setCost(int cost) {
        this.cost = cost;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public int getIsBill() {
        return this.isBill;
    }
    
    public void setIsBill(int isBill) {
        this.isBill = isBill;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Date getBillDate() {
        return billDate;
    }

    public void setBillDate(Date billDate) {
        this.billDate = billDate;
    }

    public String getRefItemId() {
        return refItemId;
    }

    public void setRefItemId(String refItemId) {
        this.refItemId = refItemId;
    }

    public String getCurCost() {
        return curCost;
    }

    public void setCurCost(String curCost) {
        this.curCost = curCost;
    }


    
}


