package com.smi.travel.datalayer.entity;
// Generated Dec 17, 2014 3:54:36 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * BookingFlight generated by hbm2java
 */
public class BookingFlight  {
    
    private String id;
    private BookingAirline bookingAirline;
    private String flightNo;
    private String sourceCode;
    private String desCode;
    private Date departureDate;
    private Date arrivalDate;
    private String flightClass;
    private String departTime;
    private String arriveTime;
    private BigDecimal adCost;
    private BigDecimal adPrice;
    private BigDecimal adTax;
    private BigDecimal chCost;
    private BigDecimal chPrice;
    private BigDecimal chTax;
    private BigDecimal inCost;
    private BigDecimal inPrice;
    private BigDecimal inTax;
    private BigDecimal otCost;
    private BigDecimal otPrice;
    private BigDecimal otTax;
    private int flightOrder;
    
    public BookingFlight() {
    }

	
    public BookingFlight(String flightNo, String sourceCode, String desCode, Date departureDate, Date arrivalDate, String flightClass) {
        this.flightNo = flightNo;
        this.sourceCode = sourceCode;
        this.desCode = desCode;
        this.departureDate = departureDate;
        this.arrivalDate = arrivalDate;
        this.flightClass = flightClass;
    }
    public BookingFlight(BookingAirline bookingAirline, String flightNo, String sourceCode, String desCode, Date departureDate, Date arrivalDate, String flightClass, String departTime, String arriveTime, BigDecimal adCost, BigDecimal adPrice, BigDecimal adTax, BigDecimal chCost, BigDecimal chPrice, BigDecimal chTax, BigDecimal inCost, BigDecimal inPrice, BigDecimal inTax) {
       this.bookingAirline = bookingAirline;
       this.flightNo = flightNo;
       this.sourceCode = sourceCode;
       this.desCode = desCode;
       this.departureDate = departureDate;
       this.arrivalDate = arrivalDate;
       this.flightClass = flightClass;
       this.departTime = departTime;
       this.arriveTime = arriveTime;
       this.adCost = adCost;
       this.adPrice = adPrice;
       this.adTax = adTax;
       this.chCost = chCost;
       this.chPrice = chPrice;
       this.chTax = chTax;
       this.inCost = inCost;
       this.inPrice = inPrice;
       this.inTax = inTax;
       this.otCost = otCost;
       this.otPrice = otPrice;
       this.otTax = otTax;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public BookingAirline getBookingAirline() {
        return this.bookingAirline;
    }
    
    public void setBookingAirline(BookingAirline bookingAirline) {
        this.bookingAirline = bookingAirline;
    }
    public String getFlightNo() {
        return this.flightNo;
    }
    
    public void setFlightNo(String flightNo) {
        this.flightNo = flightNo;
    }
    public String getSourceCode() {
        return this.sourceCode;
    }
    
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode;
    }
    public String getDesCode() {
        return this.desCode;
    }
    
    public void setDesCode(String desCode) {
        this.desCode = desCode;
    }
    public Date getDepartureDate() {
        return this.departureDate;
    }
    
    public void setDepartureDate(Date departureDate) {
        this.departureDate = departureDate;
    }
    public Date getArrivalDate() {
        return this.arrivalDate;
    }
    
    public void setArrivalDate(Date arrivalDate) {
        this.arrivalDate = arrivalDate;
    }
    public String getFlightClass() {
        return this.flightClass;
    }
    
    public void setFlightClass(String flightClass) {
        this.flightClass = flightClass;
    }
    public String getDepartTime() {
        return this.departTime;
    }
    
    public void setDepartTime(String departTime) {
        this.departTime = departTime;
    }
    public String getArriveTime() {
        return this.arriveTime;
    }
    
    public void setArriveTime(String arriveTime) {
        this.arriveTime = arriveTime;
    }

    public BigDecimal getAdCost() {
        return adCost;
    }

    public void setAdCost(BigDecimal adCost) {
        this.adCost = adCost;
    }

    public BigDecimal getAdPrice() {
        return adPrice;
    }

    public void setAdPrice(BigDecimal adPrice) {
        this.adPrice = adPrice;
    }

    public BigDecimal getAdTax() {
        return adTax;
    }

    public void setAdTax(BigDecimal adTax) {
        this.adTax = adTax;
    }

    public BigDecimal getChCost() {
        return chCost;
    }

    public void setChCost(BigDecimal chCost) {
        this.chCost = chCost;
    }

    public BigDecimal getChPrice() {
        return chPrice;
    }

    public void setChPrice(BigDecimal chPrice) {
        this.chPrice = chPrice;
    }

    public BigDecimal getChTax() {
        return chTax;
    }

    public void setChTax(BigDecimal chTax) {
        this.chTax = chTax;
    }

    public BigDecimal getInCost() {
        return inCost;
    }

    public void setInCost(BigDecimal inCost) {
        this.inCost = inCost;
    }

    public BigDecimal getInPrice() {
        return inPrice;
    }

    public void setInPrice(BigDecimal inPrice) {
        this.inPrice = inPrice;
    }

    public BigDecimal getInTax() {
        return inTax;
    }

    public void setInTax(BigDecimal inTax) {
        this.inTax = inTax;
    }

    public BigDecimal getOtCost() {
        return otCost;
    }

    public void setOtCost(BigDecimal otCost) {
        this.otCost = otCost;
    }

    public BigDecimal getOtPrice() {
        return otPrice;
    }

    public void setOtPrice(BigDecimal otPrice) {
        this.otPrice = otPrice;
    }

    public BigDecimal getOtTax() {
        return otTax;
    }

    public void setOtTax(BigDecimal otTax) {
        this.otTax = otTax;
    }

    public int getFlightOrder() {
        return flightOrder;
    }

    public void setFlightOrder(int flightOrder) {
        this.flightOrder = flightOrder;
    }

 
    
    
    

}


