package com.smi.travel.datalayer.entity;
// Generated Dec 22, 2014 4:11:19 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * BookingAirline generated by hbm2java
 */
public class BookingAirline {


     private String id;
     private BookingPnr bookingPnr;
     private String airlineCode;
     private String alrlineName;
     private Date ticketDate;
     private Set bookingPassengers = new LinkedHashSet(0);
     private Set bookingFlights = new LinkedHashSet(0);

    public BookingAirline() {
    }

	
    public BookingAirline(String airlineCode, String alrlineName, Date ticketDate) {
        this.airlineCode = airlineCode;
        this.alrlineName = alrlineName;
        this.ticketDate = ticketDate;
    }
    public BookingAirline(BookingPnr bookingPnr, String airlineCode, String alrlineName, Date ticketDate, Set bookingPassengers, Set bookingFlights) {
       this.bookingPnr = bookingPnr;
       this.airlineCode = airlineCode;
       this.alrlineName = alrlineName;
       this.ticketDate = ticketDate;
       this.bookingPassengers = bookingPassengers;
       this.bookingFlights = bookingFlights;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public BookingPnr getBookingPnr() {
        return this.bookingPnr;
    }
    
    public void setBookingPnr(BookingPnr bookingPnr) {
        this.bookingPnr = bookingPnr;
    }
    public String getAirlineCode() {
        return this.airlineCode;
    }
    
    public void setAirlineCode(String airlineCode) {
        this.airlineCode = airlineCode;
    }
    public String getAlrlineName() {
        return this.alrlineName;
    }
    
    public void setAlrlineName(String alrlineName) {
        this.alrlineName = alrlineName;
    }
    public Date getTicketDate() {
        return this.ticketDate;
    }
    
    public void setTicketDate(Date ticketDate) {
        this.ticketDate = ticketDate;
    }
    public Set getBookingPassengers() {
        return this.bookingPassengers;
    }
    
    public void setBookingPassengers(Set bookingPassengers) {
        this.bookingPassengers = bookingPassengers;
    }
    public Set getBookingFlights() {
        return this.bookingFlights;
    }
    
    public void setBookingFlights(Set bookingFlights) {
        this.bookingFlights = bookingFlights;
    }

     @Override
    public String toString() {
        return "AirlineCode[" + airlineCode +"], airlineName["+alrlineName+"], ticketDate["+ticketDate.toString()+"]";
    }
}


