package com.smi.travel.datalayer.entity;
// Generated Dec 17, 2014 3:54:36 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * BookingPnr generated by hbm2java
 */
public class BookingPnr {

    private String id;
    private String gds;
    private String pnr;
    private String filename;
    private String currency;
    private Set bookingAirlines = new LinkedHashSet(0);

    public BookingPnr() {
    }

    public BookingPnr(String gds, String pnr, String filename) {
        this.gds = gds;
        this.pnr = pnr;
        this.filename = filename;
    }

    public BookingPnr(String gds, String pnr, String filename, String currency, Set bookingAirlines) {
        this.gds = gds;
        this.pnr = pnr;
        this.filename = filename;
        this.currency = currency;
        this.bookingAirlines = bookingAirlines;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getGds() {
        return this.gds;
    }

    public void setGds(String gds) {
        this.gds = gds;
    }

    public String getPnr() {
        return this.pnr;
    }

    public void setPnr(String pnr) {
        this.pnr = pnr;
    }

    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Set getBookingAirlines() {
        return this.bookingAirlines;
    }

    public void setBookingAirlines(Set bookingAirlines) {
        this.bookingAirlines = bookingAirlines;
    }

    @Override
    public String toString() {
        return new String("BookingPnr GDS[" + gds + "], pnr[" + pnr + "], filename[" + filename + "], currency[" + currency + "]");
    }
}
