package com.smi.travel.datalayer.entity;
// Generated Mar 18, 2015 10:03:25 AM by Hibernate Tools 3.6.0



/**
 * Coupon generated by hbm2java
 */
public class Coupon  {


     private String id;
     private DaytourBooking daytourBooking;
     private OtherBooking otherBooking;

    public Coupon() {
    }

	
    public Coupon(String id) {
        this.id = id;
    }
    public Coupon(String id, DaytourBooking daytourBooking, OtherBooking otherBooking) {
       this.id = id;
       this.daytourBooking = daytourBooking;
       this.otherBooking = otherBooking;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public DaytourBooking getDaytourBooking() {
        return this.daytourBooking;
    }
    
    public void setDaytourBooking(DaytourBooking daytourBooking) {
        this.daytourBooking = daytourBooking;
    }
    public OtherBooking getOtherBooking() {
        return this.otherBooking;
    }
    
    public void setOtherBooking(OtherBooking otherBooking) {
        this.otherBooking = otherBooking;
    }




}


