package com.smi.travel.datalayer.entity;
// Generated Aug 15, 2015 12:01:47 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * CreditNoteDetail generated by hbm2java
 */
public class CreditNoteDetail  {


     private String id;
     private TaxInvoice taxInvoice;
     private MPaytype MPayType;
     private CreditNote creditNote;
     private String description;
     private BigDecimal amount;
     private BigDecimal realAmount;
     private BigDecimal vat;

    public CreditNoteDetail() {
    }

    public CreditNoteDetail(TaxInvoice taxInvoice, MPaytype MPaytype, CreditNote creditNote, String description, BigDecimal amount,BigDecimal vat) {
       this.taxInvoice = taxInvoice;
       this.MPayType = MPaytype;
       this.creditNote = creditNote;
       this.description = description;
       this.amount = amount;
       this.vat = vat;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public TaxInvoice getTaxInvoice() {
        return this.taxInvoice;
    }
    
    public void setTaxInvoice(TaxInvoice taxInvoice) {
        this.taxInvoice = taxInvoice;
    }

    public MPaytype getMPayType() {
        return MPayType;
    }

    public void setMPayType(MPaytype MPayType) {
        this.MPayType = MPayType;
    }
    
    
    
    public CreditNote getCreditNote() {
        return this.creditNote;
    }
    
    public void setCreditNote(CreditNote creditNote) {
        this.creditNote = creditNote;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public BigDecimal getVat() {
        return vat;
    }

    public void setVat(BigDecimal vat) {
        this.vat = vat;
    }

    /**
     * @return the realAmount
     */
    public BigDecimal getRealAmount() {
        return realAmount;
    }

    /**
     * @param realAmount the realAmount to set
     */
    public void setRealAmount(BigDecimal realAmount) {
        this.realAmount = realAmount;
    }




}


