package com.smi.travel.datalayer.entity;
// Generated Aug 15, 2015 12:01:47 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * CreditNoteDetail generated by hbm2java
 */
public class CreditNoteDetail  {


     private String id;
     private TaxInvoice taxInvoice;
     private MProductType MProductType;
     private CreditNote creditNote;
     private String description;
     private BigDecimal amount;

    public CreditNoteDetail() {
    }

    public CreditNoteDetail(TaxInvoice taxInvoice, MProductType MProductType, CreditNote creditNote, String description, BigDecimal amount) {
       this.taxInvoice = taxInvoice;
       this.MProductType = MProductType;
       this.creditNote = creditNote;
       this.description = description;
       this.amount = amount;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public TaxInvoice getTaxInvoice() {
        return this.taxInvoice;
    }
    
    public void setTaxInvoice(TaxInvoice taxInvoice) {
        this.taxInvoice = taxInvoice;
    }
    public MProductType getMProductType() {
        return this.MProductType;
    }
    
    public void setMProductType(MProductType MProductType) {
        this.MProductType = MProductType;
    }
    public CreditNote getCreditNote() {
        return this.creditNote;
    }
    
    public void setCreditNote(CreditNote creditNote) {
        this.creditNote = creditNote;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }




}


