package com.smi.travel.datalayer.entity;
// Generated Dec 22, 2014 5:59:06 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  {


     private String id;
     private MInitialname MInitialname;
     private String code;
     private String firstName;
     private String lastName;
     private Date birthDate;
     private String sex;
     private String address;
     private String tel;
     private String phone;
     private String postalCode;
     private String email;
     private String firstNameJapan;
     private String lastNameJapan;
     private String remark;
     private String passportNo;
     private String nationality;
     private String personalId;
     private Set masters = new HashSet(0);
     private Set passengers = new HashSet(0);


    public Customer() {
    }

	
    public Customer(MInitialname MInitialname, String code, String firstName, String lastName) {
        this.MInitialname = MInitialname;
        this.code = code;
        this.firstName = firstName;
        this.lastName = lastName;
    }
    public Customer(MInitialname MInitialname, String code, String firstName, String lastName, Date birthDate, String sex, String address, String tel, String phone, String postalCode, String email, String firstNameJapan, String lastNameJapan, String remark,String passportNo, Set masters, Set passengers,String nationality,String personalId) {
       this.MInitialname = MInitialname;
       this.code = code;
       this.firstName = firstName;
       this.lastName = lastName;
       this.birthDate = birthDate;
       this.sex = sex;
       this.address = address;
       this.tel = tel;
       this.phone = phone;
       this.postalCode = postalCode;
       this.email = email;
       this.firstNameJapan = firstNameJapan;
       this.lastNameJapan = lastNameJapan;
       this.remark = remark;
       this.passportNo = passportNo;
       this.masters = masters;
       this.passengers = passengers;
       this.nationality = nationality;
       this.personalId = personalId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public MInitialname getMInitialname() {
        return this.MInitialname;
    }
    
    public void setMInitialname(MInitialname MInitialname) {
        this.MInitialname = MInitialname;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    
  
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFirstNameJapan() {
        return this.firstNameJapan;
    }
    
    public void setFirstNameJapan(String firstNameJapan) {
        this.firstNameJapan = firstNameJapan;
    }
    public String getLastNameJapan() {
        return this.lastNameJapan;
    }
    
    public void setLastNameJapan(String lastNameJapan) {
        this.lastNameJapan = lastNameJapan;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Set getMasters() {
        return this.masters;
    }
    
    public void setMasters(Set masters) {
        this.masters = masters;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getPassportNo() {
        return passportNo;
    }

    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }

    public Set getPassengers() {
        return passengers;
    }

    public void setPassengers(Set passengers) {
        this.passengers = passengers;
    }

    public String getNationality() {
        return nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public String getPersonalId() {
        return personalId;
    }

    public void setPersonalId(String personalId) {
        this.personalId = personalId;
    }





}


