package com.smi.travel.datalayer.entity;
// Generated Mar 18, 2015 10:03:25 AM by Hibernate Tools 3.6.0

import java.math.BigDecimal;




/**
 * DaytourBookingPrice generated by hbm2java
 */
public class DaytourBookingPrice {

     private String id;
     private DaytourBooking daytourBooking;
     private MPricecategory MPricecategory;
     private String detail;
     private Integer qty;
     private BigDecimal price;
     private String currency;
     //private Integer pdefault;

    public DaytourBookingPrice() {
    }

	
    public DaytourBookingPrice(DaytourBooking daytourBooking) {
        this.daytourBooking = daytourBooking;
    }
    public DaytourBookingPrice(DaytourBooking daytourBooking, MPricecategory MPricecategory, String detail, Integer qty, BigDecimal price,String currency) {//,Integer pdefault
       this.daytourBooking = daytourBooking;
       this.MPricecategory = MPricecategory;
       this.detail = detail;
       this.qty = qty;
       this.price = price;
       this.currency = currency;
       //this.pdefault = pdefault;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public DaytourBooking getDaytourBooking() {
        return this.daytourBooking;
    }
    
    public void setDaytourBooking(DaytourBooking daytourBooking) {
        this.daytourBooking = daytourBooking;
    }
    public MPricecategory getMPricecategory() {
        return this.MPricecategory;
    }
    
    public void setMPricecategory(MPricecategory MPricecategory) {
        this.MPricecategory = MPricecategory;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }
    
//    public Integer getPdefault() {
//        return pdefault;
//    }
//
//    public void setPdefault(Integer pdefault) {
//        this.pdefault = pdefault;
//    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

}


