package com.smi.travel.datalayer.entity;
// Generated Dec 17, 2014 3:54:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Function generated by hbm2java
 */
public class Function   {


     private String id;
     private MainMenu mainMenu;
     private String name;
     private Set roleMappings = new HashSet(0);
     
    public Function() {
    }

	
    public Function(String name) {
        this.name = name;
    }
    
    public Function(MainMenu mainMenu, String name, Set roleMappings) {
       this.mainMenu = mainMenu;
       this.name = name;
       this.roleMappings = roleMappings;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getRoleMappings() {
        return this.roleMappings;
    }
    
    public void setRoleMappings(Set roleMappings) {
        this.roleMappings = roleMappings;
    }

    public MainMenu getMainMenu() {
        return mainMenu;
    }

    public void setMainMenu(MainMenu mainMenu) {
        this.mainMenu = mainMenu;
    }




}


