package com.smi.travel.datalayer.entity;
// Generated Oct 15, 2015 9:28:26 AM by Hibernate Tools 4.3.1


import com.smi.travel.datalayer.entity.Master;
import com.smi.travel.datalayer.entity.SystemUser;
import java.util.Date;

/**
 * HistoryBooking generated by hbm2java
 */
public class HistoryBooking {


     private String id;
     private Master master;
     private SystemUser staff;
     private Date historyDate;
     private String action;
     private String detail;

    public HistoryBooking() {
    }

    public HistoryBooking(Master master, SystemUser staff, Date historyDate, String action, String detail) {
       this.master = master;
       this.staff = staff;
       this.historyDate = historyDate;
       this.action = action;
       this.detail = detail;
    }
    
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
  
    public Master getMaster() {
        return this.master;
    }
    
    public void setMaster(Master master) {
        this.master = master;
    }
    
    public SystemUser getStaff() {
        return staff;
    }

    public void setStaff(SystemUser staff) {
        this.staff = staff;
    }
    
    public Date getHistoryDate() {
        return this.historyDate;
    }
    
    public void setHistoryDate(Date historyDate) {
        this.historyDate = historyDate;
    }
    
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }

}


