package com.smi.travel.datalayer.entity;
// Generated Jan 9, 2015 5:42:39 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Hotel generated by hbm2java
 */
public class Hotel  {


     private String id;
     private MCountry MCountry;
     private MCity MCity;
     private String code;
     private String name;
     private String telNo;
     private String fax;
     private String email;
     private String web;
     private String address;
     private String remark;
     private Set hotelBookings = new HashSet(0);

    public Hotel() {
    }

	
    public Hotel(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public Hotel(MCountry MCountry, MCity MCity, String code, String name, String telNo, String fax, String email, String web, String address, String remark, Set hotelBookings) {
       this.MCountry = MCountry;
       this.MCity = MCity;
       this.code = code;
       this.name = name;
       this.telNo = telNo;
       this.fax = fax;
       this.email = email;
       this.web = web;
       this.address = address;
       this.remark = remark;
       this.hotelBookings = hotelBookings;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public MCountry getMCountry() {
        return this.MCountry;
    }
    
    public void setMCountry(MCountry MCountry) {
        this.MCountry = MCountry;
    }
    public MCity getMCity() {
        return this.MCity;
    }
    
    public void setMCity(MCity MCity) {
        this.MCity = MCity;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getTelNo() {
        return this.telNo;
    }
    
    public void setTelNo(String telNo) {
        this.telNo = telNo;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Set getHotelBookings() {
        return this.hotelBookings;
    }
    
    public void setHotelBookings(Set hotelBookings) {
        this.hotelBookings = hotelBookings;
    }

}


