package com.smi.travel.datalayer.entity;
// Generated Jan 14, 2015 11:52:54 AM by Hibernate Tools 3.6.0



/**
 * HotelPassenger generated by hbm2java
 */
public class HotelPassenger   {


     private String id;
     private HotelBooking hotelBooking;
     private Passenger passenger;

    public HotelPassenger() {
    }

    public HotelPassenger(HotelBooking hotelBooking, Passenger passenger) {
       this.hotelBooking = hotelBooking;
       this.passenger = passenger;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public HotelBooking getHotelBooking() {
        return this.hotelBooking;
    }
    
    public void setHotelBooking(HotelBooking hotelBooking) {
        this.hotelBooking = hotelBooking;
    }
    public Passenger getPassenger() {
        return this.passenger;
    }
    
    public void setPassenger(Passenger passenger) {
        this.passenger = passenger;
    }




}


