package com.smi.travel.datalayer.entity;
// Generated Jan 14, 2015 11:52:54 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HotelBooking generated by hbm2java
 */
public class HotelBooking  {


     private String id;
     private MItemstatus MItemstatus;
     private Master master;
     private MMeal MMeal;
     private Hotel hotel;
     private int orderNo;
     private String reconfirm;
     private String hotelRef;
     private Integer isBill;
     private String remark;
     private Date checkin;
     private Date checkout;
     private Integer adult;
     private Integer child;
     private Integer infant;
     private String flight;
     private Date deadline;
     private Set hotelPassengers = new HashSet(0);
     private Set hotelRooms = new HashSet(0);
     private Set hotelRequests = new HashSet(0);

    public HotelBooking() {
    }

	
    public HotelBooking(MItemstatus MItemstatus, Master master, Hotel hotel, int orderNo, Date checkin, Date checkout) {
        this.MItemstatus = MItemstatus;
        this.master = master;
        this.hotel = hotel;
        this.orderNo = orderNo;
        this.checkin = checkin;
        this.checkout = checkout;
    }
    public HotelBooking(MItemstatus MItemstatus, Master master, MMeal MMeal, Hotel hotel, int orderNo, String reconfirm, String hotelRef, Integer isBill, String remark, Date checkin, Date checkout, Integer adult, Integer child, Integer infant, Set hotelPassengers, Set hotelRooms, Set hotelRequests) {
       this.MItemstatus = MItemstatus;
       this.master = master;
       this.MMeal = MMeal;
       this.hotel = hotel;
       this.orderNo = orderNo;
       this.reconfirm = reconfirm;
       this.hotelRef = hotelRef;
       this.isBill = isBill;
       this.remark = remark;
       this.checkin = checkin;
       this.checkout = checkout;
       this.adult = adult;
       this.child = child;
       this.infant = infant;
       this.deadline =deadline;
       this.flight= flight;
       this.hotelPassengers = hotelPassengers;
       this.hotelRooms = hotelRooms;
       this.hotelRequests = hotelRequests;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public MItemstatus getMItemstatus() {
        return this.MItemstatus;
    }
    
    public void setMItemstatus(MItemstatus MItemstatus) {
        this.MItemstatus = MItemstatus;
    }
    public Master getMaster() {
        return this.master;
    }
    
    public void setMaster(Master master) {
        this.master = master;
    }
    public MMeal getMMeal() {
        return this.MMeal;
    }
    
    public void setMMeal(MMeal MMeal) {
        this.MMeal = MMeal;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public int getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(int orderNo) {
        this.orderNo = orderNo;
    }
    public String getReconfirm() {
        return this.reconfirm;
    }
    
    public void setReconfirm(String reconfirm) {
        this.reconfirm = reconfirm;
    }
    public String getHotelRef() {
        return this.hotelRef;
    }
    
    public void setHotelRef(String hotelRef) {
        this.hotelRef = hotelRef;
    }
    public Integer getIsBill() {
        return this.isBill;
    }
    
    public void setIsBill(Integer isBill) {
        this.isBill = isBill;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Date getCheckin() {
        return this.checkin;
    }
    
    public void setCheckin(Date checkin) {
        this.checkin = checkin;
    }
    public Date getCheckout() {
        return this.checkout;
    }
    
    public void setCheckout(Date checkout) {
        this.checkout = checkout;
    }
    public Integer getAdult() {
        return this.adult;
    }
    
    public void setAdult(Integer adult) {
        this.adult = adult;
    }
    public Integer getChild() {
        return this.child;
    }
    
    public void setChild(Integer child) {
        this.child = child;
    }
    public Integer getInfant() {
        return this.infant;
    }
    
    public void setInfant(Integer infant) {
        this.infant = infant;
    }
    public Set getHotelPassengers() {
        return this.hotelPassengers;
    }
    
    public void setHotelPassengers(Set hotelPassengers) {
        this.hotelPassengers = hotelPassengers;
    }
    public Set getHotelRooms() {
        return this.hotelRooms;
    }
    
    public void setHotelRooms(Set hotelRooms) {
        this.hotelRooms = hotelRooms;
    }
    public Set getHotelRequests() {
        return this.hotelRequests;
    }
    
    public void setHotelRequests(Set hotelRequests) {
        this.hotelRequests = hotelRequests;
    }

    public String getFlight() {
        return flight;
    }

    public void setFlight(String flight) {
        this.flight = flight;
    }

    public Date getDeadline() {
        return deadline;
    }

    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }




}


