package com.smi.travel.datalayer.entity;
// Generated Jan 14, 2015 11:52:54 AM by Hibernate Tools 3.6.0

import java.math.BigDecimal;




/**
 * HotelRequest generated by hbm2java
 */
public class HotelRequest  {


     private String id;
     private HotelBooking hotelBooking;
     private String category;
     private String description;
     private BigDecimal cost;
     private BigDecimal price;
     private String currency;


    public HotelRequest() {
    }

	
    public HotelRequest(HotelBooking hotelBooking, String description, BigDecimal cost, BigDecimal price,String currency) {
        this.hotelBooking = hotelBooking;
        this.description = description;
        this.cost = cost;
        this.price = price;
        this.currency = currency;
    }
    public HotelRequest(HotelBooking hotelBooking, String category, String description, BigDecimal cost, BigDecimal price,String currency) {
       this.hotelBooking = hotelBooking;
       this.category = category;
       this.description = description;
       this.cost = cost;
       this.price = price;
       this.currency = currency;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public HotelBooking getHotelBooking() {
        return this.hotelBooking;
    }
    
    public void setHotelBooking(HotelBooking hotelBooking) {
        this.hotelBooking = hotelBooking;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public BigDecimal getCost() {
        return cost;
    }

    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

}


