package com.smi.travel.datalayer.entity;
// Generated Jan 14, 2015 11:52:54 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;


/**
 * HotelBooking generated by hbm2java
 */
public class HotelBooking  {
    
     private String id;
     private MItemstatus MItemstatus;
     private Master master;
     private MMeal MMeal;
     private Hotel hotel;
     private int orderNo;
     private String reconfirm;
     private String hotelRef;
     private Integer isBill;
     private String remark;
     private Date checkin;
     private Date checkout;
     private Integer adult;
     private Integer child;
     private Integer infant;
     private String flight;
     private Date deadline;
     private String curAmount;
     private String curCost;
     private Integer totalcost;
     private String supplier;
     private List hotelPassengers = new LinkedList<HotelPassenger>();
     private List hotelRooms = new LinkedList<HotelRoom>();
     private List hotelRequests = new LinkedList<HotelRequest>();
     private BigDecimal sumRoom;
     private BigDecimal sumRequest;
     private BigDecimal sumTotalCost;

    public HotelBooking() {
    }

	
    public HotelBooking(MItemstatus MItemstatus, Master master, Hotel hotel, int orderNo, Date checkin, Date checkout) {
        this.MItemstatus = MItemstatus;
        this.master = master;
        this.hotel = hotel;
        this.orderNo = orderNo;
        this.checkin = checkin;
        this.checkout = checkout;
    }
    public HotelBooking(MItemstatus MItemstatus, Master master, MMeal MMeal, Hotel hotel, int orderNo, String reconfirm, String hotelRef, Integer isBill, String remark, Date checkin, Date checkout, Integer adult, Integer child, Integer infant,String currency, List hotelPassengers, List hotelRooms, List hotelRequests,String curAmount,String curCost,String supplier, BigDecimal sumRoom, BigDecimal sumRequest, BigDecimal sumTotalCost) {
       this.MItemstatus = MItemstatus;
       this.master = master;
       this.MMeal = MMeal;
       this.hotel = hotel;
       this.orderNo = orderNo;
       this.reconfirm = reconfirm;
       this.hotelRef = hotelRef;
       this.isBill = isBill;
       this.remark = remark;
       this.checkin = checkin;
       this.checkout = checkout;
       this.adult = adult;
       this.child = child;
       this.infant = infant;
       this.deadline =deadline;
       this.flight= flight;
       this.curAmount = curAmount;
       this.curCost = curCost;
       this.hotelPassengers = hotelPassengers;
       this.hotelRooms = hotelRooms;
       this.hotelRequests = hotelRequests;
       this.supplier = supplier;
       this.sumRoom = sumRoom;
       this.sumRequest = sumRequest;
       this.sumTotalCost = sumTotalCost;
    }

    public String getSupplier() {
        return supplier;
    }

    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public MItemstatus getMItemstatus() {
        return this.MItemstatus;
    }
    
    public void setMItemstatus(MItemstatus MItemstatus) {
        this.MItemstatus = MItemstatus;
    }
    public Master getMaster() {
        return this.master;
    }
    
    public void setMaster(Master master) {
        this.master = master;
    }
    public MMeal getMMeal() {
        return this.MMeal;
    }

    public String getCurAmount() {
        return curAmount;
    }

    public void setCurAmount(String curAmount) {
        this.curAmount = curAmount;
    }

    public String getCurCost() {
        return curCost;
    }

    public void setCurCost(String curCost) {
        this.curCost = curCost;
    }

    
    
    
    
    public void setMMeal(MMeal MMeal) {
        this.MMeal = MMeal;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public int getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(int orderNo) {
        this.orderNo = orderNo;
    }
    public String getReconfirm() {
        return this.reconfirm;
    }
    
    public void setReconfirm(String reconfirm) {
        this.reconfirm = reconfirm;
    }
    public String getHotelRef() {
        return this.hotelRef;
    }
    
    public void setHotelRef(String hotelRef) {
        this.hotelRef = hotelRef;
    }
    public Integer getIsBill() {
        return this.isBill;
    }
    
    public void setIsBill(Integer isBill) {
        this.isBill = isBill;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Date getCheckin() {
        return this.checkin;
    }
    
    public void setCheckin(Date checkin) {
        this.checkin = checkin;
    }
    public Date getCheckout() {
        return this.checkout;
    }
    
    public void setCheckout(Date checkout) {
        this.checkout = checkout;
    }
    public Integer getAdult() {
        return this.adult;
    }
    
    public void setAdult(Integer adult) {
        this.adult = adult;
    }
    public Integer getChild() {
        return this.child;
    }
    
    public void setChild(Integer child) {
        this.child = child;
    }
    public Integer getInfant() {
        return this.infant;
    }
    
    public void setInfant(Integer infant) {
        this.infant = infant;
    }
    public List getHotelPassengers() {
        return this.hotelPassengers;
    }
    
    public void setHotelPassengers(List hotelPassengers) {
        this.hotelPassengers = hotelPassengers;
    }
    public List getHotelRooms() {
        return this.hotelRooms;
    }
    
    public void setHotelRooms(List hotelRooms) {
        this.hotelRooms = hotelRooms;
    }
    public List getHotelRequests() {
        return this.hotelRequests;
    }
    
    public void setHotelRequests(List hotelRequests) {
        this.hotelRequests = hotelRequests;
    }

    public String getFlight() {
        return flight;
    }

    public void setFlight(String flight) {
        this.flight = flight;
    }

    public Date getDeadline() {
        return deadline;
    }

    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    public Integer getTotalcost() {
        return totalcost;
    }

    public void setTotalcost(Integer totalcost) {
        this.totalcost = totalcost;
    }

    public BigDecimal getSumRoom() {
        return sumRoom;
    }

    public void setSumRoom(BigDecimal sumRoom) {
        this.sumRoom = sumRoom;
    }

    public BigDecimal getSumRequest() {
        return sumRequest;
    }

    public void setSumRequest(BigDecimal sumRequest) {
        this.sumRequest = sumRequest;
    }

    public BigDecimal getSumTotalCost() {
        return sumTotalCost;
    }

    public void setSumTotalCost(BigDecimal sumTotalCost) {
        this.sumTotalCost = sumTotalCost;
    }




}


