package com.smi.travel.datalayer.entity;
// Generated Jul 20, 2015 5:19:24 PM by Hibernate Tools 4.3.1
import java.math.BigDecimal;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

/**
 * InvoiceDetail generated by hbm2java
 */
public class InvoiceDetail {


     private String id;
     private BillableDesc billableDesc;
     private Invoice invoice;
     private MBilltype mbillType;
     private String description;
     private BigDecimal cost;
     private BigDecimal costLocal;
     private String curCost;
     private BigDecimal amount;
     private BigDecimal amountLocal;
     private String curAmount;
     private BigDecimal vat;
     private BigDecimal gross;
     private Integer isVat;
     private Date exportDate;
     private Integer isExport;
     private String displayDescription;
     private BigDecimal exRate;
     private List invoiceDocuments = new LinkedList<InvoiceDocument>();
     private List receiptDetails = new LinkedList<ReceiptDetail>();
     
     
    public InvoiceDetail() {
    }

	
    public InvoiceDetail(Invoice invoice) {
        this.invoice = invoice;
    }
    public InvoiceDetail(BillableDesc billableDesc, Invoice invoice, MBilltype mbillType, String description, BigDecimal cost, BigDecimal costLocal, String curCost, BigDecimal amount, BigDecimal amountLocal, String curAmount, BigDecimal vat, Integer isVat, List invoiceDocuments,BigDecimal gross,String displayDescription,Date exportDate,Integer isExport,List receiptDetails ) {
       this.billableDesc = billableDesc;
       this.invoice = invoice;
       this.mbillType = mbillType;
       this.description = description;
       this.cost = cost;
       this.costLocal = costLocal;
       this.curCost = curCost;
       this.amount = amount;
       this.amountLocal = amountLocal;
       this.curAmount = curAmount;
       this.vat = vat;
       this.isVat = isVat;
       this.displayDescription = displayDescription;
       this.invoiceDocuments = invoiceDocuments;
       this.receiptDetails = receiptDetails;
       this.exportDate = exportDate;
       this.isExport = isExport;
    }
   
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getDisplayDescription() {
        return displayDescription;
    }

    public void setDisplayDescription(String displayDescription) {
        this.displayDescription = displayDescription;
    }
    
    public Integer getIsExport() {
        return isExport;
    }

    public Date getExportDate() {
        return exportDate;
    }

     public void setIsExport(Integer isExport) {
        this.isExport = isExport;
    }

    public void setExportDate(Date exportDate) {
        this.exportDate = exportDate;
    }

    
    public BillableDesc getBillableDesc() {
        return this.billableDesc;
    }
    
    public void setBillableDesc(BillableDesc billableDesc) {
        this.billableDesc = billableDesc;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }

    public MBilltype getMbillType() {
        return mbillType;
    }

    public void setMbillType(MBilltype mbillType) {
        this.mbillType = mbillType;
    }
   
    
    
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
    public BigDecimal getCostLocal() {
        return this.costLocal;
    }
    
    public void setCostLocal(BigDecimal costLocal) {
        this.costLocal = costLocal;
    }
    public String getCurCost() {
        return this.curCost;
    }
    
    public void setCurCost(String curCost) {
        this.curCost = curCost;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public BigDecimal getAmountLocal() {
        return this.amountLocal;
    }
    
    public void setAmountLocal(BigDecimal amountLocal) {
        this.amountLocal = amountLocal;
    }
    public String getCurAmount() {
        return this.curAmount;
    }
    
    public void setCurAmount(String curAmount) {
        this.curAmount = curAmount;
    }
    public BigDecimal getVat() {
        return this.vat;
    }
    
    public void setVat(BigDecimal vat) {
        this.vat = vat;
    }

    public BigDecimal getGross() {
        return gross;
    }

    public void setGross(BigDecimal gross) {
        this.gross = gross;
    }

    public Integer getIsVat() {
        return isVat;
    }

    public void setIsVat(Integer isVat) {
        this.isVat = isVat;
    }
     

    public List getInvoiceDocuments() {
        return invoiceDocuments;
    }

    public void setInvoiceDocuments(List invoiceDocuments) {
        this.invoiceDocuments = invoiceDocuments;
    }

    public List getReceiptDetails() {
        return receiptDetails;
    }

    public void setReceiptDetails(List receiptDetails) {
        this.receiptDetails = receiptDetails;
    }

    public BigDecimal getExRate() {
        return exRate;
    }

    public void setExRate(BigDecimal exRate) {
        this.exRate = exRate;
    }




}


