package com.smi.travel.datalayer.entity;
// Generated Jul 20, 2015 5:19:24 PM by Hibernate Tools 4.3.1



/**
 * InvoiceDocument generated by hbm2java
 */
public class InvoiceDocument {


     private String id;
     private InvoiceDetail invoiceDetail;
     private String description;

    public InvoiceDocument() {
    }

	
    public InvoiceDocument(InvoiceDetail invoiceDetail) {
        this.invoiceDetail = invoiceDetail;
    }
    public InvoiceDocument(InvoiceDetail invoiceDetail, String description) {
       this.invoiceDetail = invoiceDetail;
       this.description = description;
    }
   
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public InvoiceDetail getInvoiceDetail() {
        return this.invoiceDetail;
    }
    
    public void setInvoiceDetail(InvoiceDetail invoiceDetail) {
        this.invoiceDetail = invoiceDetail;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


