package com.smi.travel.datalayer.entity;
// Generated Jul 20, 2015 5:19:24 PM by Hibernate Tools 4.3.1


import com.smi.travel.datalayer.entity.MAccpay;
import com.smi.travel.datalayer.entity.MFinanceItemstatus;
import com.smi.travel.datalayer.entity.SystemUser;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

/**
 * Invoice generated by hbm2java
 */
public class Invoice {


     private String id;
     private MAccpay MAccpay;
     private MFinanceItemstatus MFinanceItemstatus;
     private SystemUser staff;
     private String invNo;
     private String invTo;
     private String invName;
     private String invAddress;
     private Date dueDate;
     private String deparement;
     private String arcode;
     private String remark;
     private String invType;
     private Integer isGroup;
     private Integer isLock;
     private String createBy;
     private Date createDate;
     private String subDepartment;
     private List invoiceDetails = new LinkedList<InvoiceDetail>();

    public Invoice() {
    }

    public Invoice(MAccpay MAccpay, MFinanceItemstatus MFinanceItemstatus, SystemUser staff, String invNo, String invTo, String invName, String invAddress, Date dueDate, String deparement, String arcode, String remark, String invType, Integer isGroup, Integer isLock, String createBy, Date createDate, String subDepartment, List invoiceDetails) {
       this.MAccpay = MAccpay;
       this.MFinanceItemstatus = MFinanceItemstatus;
       this.staff = staff;
       this.invNo = invNo;
       this.invTo = invTo;
       this.invName = invName;
       this.invAddress = invAddress;
       this.dueDate = dueDate;
       this.deparement = deparement;
       this.arcode = arcode;
       this.remark = remark;
       this.invType = invType;
       this.isGroup = isGroup;
       this.isLock = isLock;
       this.createBy = createBy;
       this.createDate = createDate;
       this.subDepartment = subDepartment;
       this.invoiceDetails = invoiceDetails;
    }
   
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public MAccpay getMAccpay() {
        return this.MAccpay;
    }
    
    public void setMAccpay(MAccpay MAccpay) {
        this.MAccpay = MAccpay;
    }
    public MFinanceItemstatus getMFinanceItemstatus() {
        return this.MFinanceItemstatus;
    }
    
    public void setMFinanceItemstatus(MFinanceItemstatus MFinanceItemstatus) {
        this.MFinanceItemstatus = MFinanceItemstatus;
    }

    public SystemUser getStaff() {
        return staff;
    }

    public void setStaff(SystemUser staff) {
        this.staff = staff;
    }
    
    public String getInvNo() {
        return this.invNo;
    }
    
    public void setInvNo(String invNo) {
        this.invNo = invNo;
    }
    public String getInvTo() {
        return this.invTo;
    }
    
    public void setInvTo(String invTo) {
        this.invTo = invTo;
    }
    public String getInvName() {
        return this.invName;
    }
    
    public void setInvName(String invName) {
        this.invName = invName;
    }
    public String getInvAddress() {
        return this.invAddress;
    }
    
    public void setInvAddress(String invAddress) {
        this.invAddress = invAddress;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public String getDeparement() {
        return this.deparement;
    }
    
    public void setDeparement(String deparement) {
        this.deparement = deparement;
    }

    public void setArcode(String arcode) {
        this.arcode = arcode;
    }

    public String getArcode() {
        return arcode;
    }
   
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public String getInvType() {
        return this.invType;
    }
    
    public void setInvType(String invType) {
        this.invType = invType;
    }
    public Integer getIsGroup() {
        return this.isGroup;
    }
    
    public void setIsGroup(Integer isGroup) {
        this.isGroup = isGroup;
    }
    public Integer getIsLock() {
        return this.isLock;
    }
    
    public void setIsLock(Integer isLock) {
        this.isLock = isLock;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public String getSubDepartment() {
        return this.subDepartment;
    }
    
    public void setSubDepartment(String subDepartment) {
        this.subDepartment = subDepartment;
    }

    public List getInvoiceDetails() {
        return invoiceDetails;
    }

    public void setInvoiceDetails(List invoiceDetails) {
        this.invoiceDetails = invoiceDetails;
    }





}


