package com.smi.travel.datalayer.entity;
// Generated Mar 1, 2016 9:47:45 AM by Hibernate Tools 4.3.1

/**
 * LandCity generated by hbm2java
 */
public class LandCity {

     private String id;
     private LandBooking landBooking;
     private MCity MCity;

    public LandCity() {
    }

	
    public LandCity(LandBooking landBooking) {
        this.landBooking = landBooking;
    }
    
    public LandCity(LandBooking landBooking, MCity MCity) {
       this.landBooking = landBooking;
       this.MCity = MCity;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    public LandBooking getLandBooking() {
        return this.landBooking;
    }
    
    public void setLandBooking(LandBooking landBooking) {
        this.landBooking = landBooking;
    }
    public MCity getMCity() {
        return this.MCity;
    }
    
    public void setMCity(MCity MCity) {
        this.MCity = MCity;
    }
    
}


