package com.smi.travel.datalayer.entity;
// Generated Jan 25, 2015 3:19:47 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * LandItinerary generated by hbm2java
 */
public class LandItinerary  {

     private String id;
     private LandBooking landBooking;
     private String packagecode;
     private int orderNo;
     private Date dayTime;
     private Date dayDate;
     private String description;

    public LandItinerary() {
        
    }

    public LandItinerary(LandBooking landBooking, int orderNo,String packagecode, Date dayTime, Date dayDate, String description) {
       this.landBooking = landBooking;
       this.packagecode = packagecode;
       this.orderNo = orderNo;
       this.dayTime = dayTime;
       this.dayDate = dayDate;
       this.description = description;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public LandBooking getLandBooking() {
        return this.landBooking;
    }
    
    public void setLandBooking(LandBooking landBooking) {
        this.landBooking = landBooking;
    }
    public int getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(int orderNo) {
        this.orderNo = orderNo;
    }
    public Date getDayTime() {
        return this.dayTime;
    }
    
    public void setDayTime(Date dayTime) {
        this.dayTime = dayTime;
    }
    public Date getDayDate() {
        return this.dayDate;
    }
    
    public void setDayDate(Date dayDate) {
        this.dayDate = dayDate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getPackagecode() {
        return packagecode;
    }

    public void setPackagecode(String packagecode) {
        this.packagecode = packagecode;
    }




}


