package com.smi.travel.datalayer.entity;
// Generated Dec 22, 2014 5:59:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MAccterm generated by hbm2java
 */
public class MAccterm   {


     private String id;
     private String code;
     private String name;
     private Integer value;
     private Set agents = new HashSet(0);

    public MAccterm() {
    }

	
    public MAccterm(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public MAccterm(String code, String name,Integer value, Set agents) {
       this.code = code;
       this.name = name;
       this.value = value;
       this.agents = agents;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getAgents() {
        return this.agents;
    }
    
    public void setAgents(Set agents) {
        this.agents = agents;
    }

    public Integer getValue() {
        return value;
    }

    public void setValue(Integer value) {
        this.value = value;
    }




}


