package com.smi.travel.datalayer.entity;
// Generated Dec 24, 2014 10:24:56 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MAccpay generated by hbm2java
 */
public class MAccpay  {


     private String id;
     private String code;
     private String name;
     private Set billables = new HashSet(0);

    public MAccpay() {
    }

	
    public MAccpay(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public MAccpay(String code, String name, Set billables) {
       this.code = code;
       this.name = name;
       this.billables = billables;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getBillables() {
        return this.billables;
    }
    
    public void setBillables(Set billables) {
        this.billables = billables;
    }




}


