package com.smi.travel.datalayer.entity;
// Generated Jan 12, 2015 10:34:40 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MainMenu generated by hbm2java
 */
public class MainMenu  {


     private String id;
     private String name;
     private Set functions = new HashSet(0);

    public MainMenu() {
    }

	
    public MainMenu(String name) {
        this.name = name;
    }
    public MainMenu(String name, Set functions) {
       this.name = name;
       this.functions = functions;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getFunctions() {
        return this.functions;
    }
    
    public void setFunctions(Set functions) {
        this.functions = functions;
    }




}


