package com.smi.travel.datalayer.entity;
// Generated Jul 9, 2015 9:38:50 AM by Hibernate Tools 4.3.1

import java.util.LinkedList;
import java.util.List;


/**
 * MAirlineAgent generated by hbm2java
 */
public class MAirlineAgent {

    
     private String id;
     private String code;
     private String name;
     private List ticketFareAirlines = new LinkedList<TicketFareAirline>();

    public MAirlineAgent() {
    }

    public MAirlineAgent(String code, String name) {
        this.code = code;
        this.name = name;
    }
    
    public MAirlineAgent(String code, String name, List ticketFareAirlines) {
       this.code = code;
       this.name = name;
       this.ticketFareAirlines = ticketFareAirlines;
    }
   
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public List getTicketFareAirlines() {
        return ticketFareAirlines;
    }

    public void setTicketFareAirlines(List ticketFareAirlines) {
        this.ticketFareAirlines = ticketFareAirlines;
    }

}


