package com.smi.travel.datalayer.entity;
// Generated Jun 9, 2016 2:31:36 PM by Hibernate Tools 4.3.1



/**
 * MBankNirvana generated by hbm2java
 */
public class MBankNirvana {


     private String id;
     private String code;
     private String name;

    public MBankNirvana() {
    }

    public MBankNirvana(String code, String name) {
       this.code = code;
       this.name = name;
    }
   
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


