package com.smi.travel.datalayer.entity;
// Generated Jan 5, 2015 2:05:28 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MBookingstatus generated by hbm2java
 */
public class MBookingstatus {


     private String id;
     private String name;
     private Set masters = new HashSet(0);

    public MBookingstatus() {
    }

	
    public MBookingstatus(String name) {
        this.name = name;
    }
    public MBookingstatus(String name , Set masters) {
       this.name = name;
       this.masters = masters;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Set getMasters() {
        return this.masters;
    }
    
    public void setMasters(Set masters) {
        this.masters = masters;
    }




}


