package com.smi.travel.datalayer.entity;
// Generated Dec 4, 2014 5:36:02 PM by Hibernate Tools 3.6.0



/**
 * MCountry generated by hbm2java
 */
public class MCountry {


     private String id;
     private String code;
     private String name;

    public MCountry() {
    }

    public MCountry(String code, String name) {
       this.code = code;
       this.name = name;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


