package com.smi.travel.datalayer.entity;
// Generated Dec 4, 2014 5:36:02 PM by Hibernate Tools 3.6.0



/**
 * MCurrency generated by hbm2java
 */
public class MCurrency  {


     private String id;
     private String code;
     private String description;

    public MCurrency() {
    }

	
    public MCurrency(String code) {
        this.code = code;
    }
    public MCurrency(String code, String description) {
       this.code = code;
       this.description = description;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


