package com.smi.travel.datalayer.entity;
// Generated Jan 9, 2015 5:42:39 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MDepartment generated by hbm2java
 */
public class MDepartment   {


     private String id;
     private String name;
     private Set staffs = new HashSet(0);

    public MDepartment() {
    }

	
    public MDepartment(String name) {
        this.name = name;
    }
    public MDepartment(String name, Set staffs) {
       this.name = name;
       this.staffs = staffs;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }




}


