package com.smi.travel.datalayer.entity;
// Generated Jul 20, 2015 5:19:24 PM by Hibernate Tools 4.3.1

import java.util.LinkedList;
import java.util.List;





/**
 * MFinanceItemstatus generated by hbm2java
 */
public class MFinanceItemstatus {


     private String id;
     private String name;
     private List invoices = new LinkedList<Invoice>();
     
    public MFinanceItemstatus() {
    }

	
    public MFinanceItemstatus(String name) {
        this.name = name;
    }
    public MFinanceItemstatus(String name, List invoices) {
       this.name = name;
       this.invoices = invoices;
    }
   
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public List getInvoices() {
        return invoices;
    }

    public void setInvoices(List invoices) {
        this.invoices = invoices;
    }




}


