package com.smi.travel.datalayer.entity;
// Generated Aug 6, 2015 3:13:50 PM by Hibernate Tools 4.3.1

import java.util.List;


/**
 * MFlightservice generated by hbm2java
 */
public class MFlightservice {
     private String id;
     private MFlight MFlight;
     private String classCode;
     private String className;

    public MFlightservice() {
    }

    public MFlightservice(MFlight MFlight, String classCode, String className) {
       this.MFlight = MFlight;
       this.classCode = classCode;
       this.className = className;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public MFlight getMFlight() {
        return this.MFlight;
    }
    
    public void setMFlight(MFlight MFlight) {
        this.MFlight = MFlight;
    }
    public String getClassCode() {
        return this.classCode;
    }
    
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }


}


