package com.smi.travel.datalayer.entity;
// Generated Dec 22, 2014 5:59:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MInitialname generated by hbm2java
 */
public class MInitialname  {


     private String id;
     private String code;
     private String name;
     private Set customers = new HashSet(0);

    public MInitialname() {
    }

	
    public MInitialname(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public MInitialname(String code, String name, Set customers) {
       this.code = code;
       this.name = name;
       this.customers = customers;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


