package com.smi.travel.datalayer.entity;
// Generated Dec 23, 2014 9:31:32 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MItemstatus generated by hbm2java
 */
public class MItemstatus  {


     private String id;
     private String name;
   private Set airticketFlights = new HashSet(0);

    public MItemstatus() {
    }

	
    public MItemstatus(String name) {
        this.name = name;
    }
    public MItemstatus(String name, Set airticketFlights) {
       this.name = name;
       this.airticketFlights = airticketFlights;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getAirticketFlights() {
        return this.airticketFlights;
    }
    
    public void setAirticketFlights(Set airticketFlights) {
        this.airticketFlights = airticketFlights;
    }




}


