package com.smi.travel.datalayer.entity;
// Generated Dec 17, 2014 3:54:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MPlacestatus generated by hbm2java
 */
public class MPlacestatus{

     private String id;
     private String name;
     private Set places = new HashSet(0);

    public MPlacestatus() {
    }

	
    public MPlacestatus(String name) {
        this.name = name;
    }
    public MPlacestatus(String name, Set places) {
       this.name = name;
       this.places = places;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getPlaces() {
        return this.places;
    }
    
    public void setPlaces(Set places) {
        this.places = places;
    }




}


