package com.smi.travel.datalayer.entity;
// Generated Dec 23, 2014 9:06:11 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MPricecategory generated by hbm2java
 */
public class MPricecategory  {


     private String id;
     private String code;
     private String name;
     private Set airticketPassengers = new HashSet(0);

    public MPricecategory() {
    }

	
    public MPricecategory(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public MPricecategory(String code, String name, Set airticketPassengers) {
       this.code = code;
       this.name = name;
       this.airticketPassengers = airticketPassengers;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getAirticketPassengers() {
        return this.airticketPassengers;
    }
    
    public void setAirticketPassengers(Set airticketPassengers) {
        this.airticketPassengers = airticketPassengers;
    }




}


