package com.smi.travel.datalayer.entity;
// Generated Jan 9, 2015 5:42:39 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MProductType generated by hbm2java
 */
public class MProductType  {


    private String id;
    private String name;
    private Set products = new HashSet(0);

    public MProductType() {
    }

    public MProductType(String name, Set products) {
       this.name = name;
       this.products = products;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


