package com.smi.travel.datalayer.entity;
// Generated Apr 17, 2015 1:56:04 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * PackageItinerary generated by hbm2java
 */
public class PackageItinerary  {


     private String id;
     private PackageTour packageTour;
     private Integer orderNo;
     private Date time;
     private String detail;

    public PackageItinerary() {
    }

	
    public PackageItinerary(PackageTour packageTour) {
        this.packageTour = packageTour;
    }
    public PackageItinerary(PackageTour packageTour, Integer orderNo, Date time, String detail) {
       this.packageTour = packageTour;
       this.orderNo = orderNo;
       this.time = time;
       this.detail = detail;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public PackageTour getPackageTour() {
        return this.packageTour;
    }
    
    public void setPackageTour(PackageTour packageTour) {
        this.packageTour = packageTour;
    }
    public Integer getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }




}


