package com.smi.travel.datalayer.entity;
// Generated Apr 17, 2015 1:56:04 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * PackagePrice generated by hbm2java
 */
public class PackagePrice {


     private String id;
     private PackageTour packageTour;
     private Date effectiveFrom;
     private Date effectiveTo;
     private Integer adCost;
     private Integer chCost;
     private Integer inCost;
     private Integer adPrice;
     private Integer chPrice;
     private Integer inPrice;
     private String updateBy;

    public PackagePrice() {
    }

	
    public PackagePrice(PackageTour packageTour) {
        this.packageTour = packageTour;
    }
    public PackagePrice(PackageTour packageTour, Date effectiveFrom, Date effectiveTo, Integer adCost, Integer chCost, Integer inCost, Integer adPrice, Integer chPrice, Integer inPrice, String updateBy) {
       this.packageTour = packageTour;
       this.effectiveFrom = effectiveFrom;
       this.effectiveTo = effectiveTo;
       this.adCost = adCost;
       this.chCost = chCost;
       this.inCost = inCost;
       this.adPrice = adPrice;
       this.chPrice = chPrice;
       this.inPrice = inPrice;
       this.updateBy = updateBy;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public PackageTour getPackageTour() {
        return this.packageTour;
    }
    
    public void setPackageTour(PackageTour packageTour) {
        this.packageTour = packageTour;
    }
    public Date getEffectiveFrom() {
        return this.effectiveFrom;
    }
    
    public void setEffectiveFrom(Date effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }
    public Date getEffectiveTo() {
        return this.effectiveTo;
    }
    
    public void setEffectiveTo(Date effectiveTo) {
        this.effectiveTo = effectiveTo;
    }
    public Integer getAdCost() {
        return this.adCost;
    }
    
    public void setAdCost(Integer adCost) {
        this.adCost = adCost;
    }
    public Integer getChCost() {
        return this.chCost;
    }
    
    public void setChCost(Integer chCost) {
        this.chCost = chCost;
    }
    public Integer getInCost() {
        return this.inCost;
    }
    
    public void setInCost(Integer inCost) {
        this.inCost = inCost;
    }
    public Integer getAdPrice() {
        return this.adPrice;
    }
    
    public void setAdPrice(Integer adPrice) {
        this.adPrice = adPrice;
    }
    public Integer getChPrice() {
        return this.chPrice;
    }
    
    public void setChPrice(Integer chPrice) {
        this.chPrice = chPrice;
    }
    public Integer getInPrice() {
        return this.inPrice;
    }
    
    public void setInPrice(Integer inPrice) {
        this.inPrice = inPrice;
    }
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }




}


