package com.smi.travel.datalayer.entity;
// Generated Apr 17, 2015 1:56:04 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * PackagePrice generated by hbm2java
 */
public class PackagePrice {


     private String id;
     private PackageTour packageTour;
     private Date effectiveFrom;
     private Date effectiveTo;
     private BigDecimal adCost;
     private BigDecimal chCost;
     private BigDecimal inCost;
     private BigDecimal adPrice;
     private BigDecimal chPrice;
     private BigDecimal inPrice;
     private String updateBy;

    public PackagePrice() {
    }

	
    public PackagePrice(PackageTour packageTour) {
        this.packageTour = packageTour;
    }
    public PackagePrice(PackageTour packageTour, Date effectiveFrom, Date effectiveTo, BigDecimal adCost, BigDecimal chCost, BigDecimal inCost, BigDecimal adPrice, BigDecimal chPrice, BigDecimal inPrice, String updateBy) {
       this.packageTour = packageTour;
       this.effectiveFrom = effectiveFrom;
       this.effectiveTo = effectiveTo;
       this.adCost = adCost;
       this.chCost = chCost;
       this.inCost = inCost;
       this.adPrice = adPrice;
       this.chPrice = chPrice;
       this.inPrice = inPrice;
       this.updateBy = updateBy;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public PackageTour getPackageTour() {
        return this.packageTour;
    }
    
    public void setPackageTour(PackageTour packageTour) {
        this.packageTour = packageTour;
    }
    public Date getEffectiveFrom() {
        return this.effectiveFrom;
    }
    
    public void setEffectiveFrom(Date effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }
    public Date getEffectiveTo() {
        return this.effectiveTo;
    }
    
    public void setEffectiveTo(Date effectiveTo) {
        this.effectiveTo = effectiveTo;
    }
    
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public BigDecimal getAdCost() {
        return adCost;
    }

    public void setAdCost(BigDecimal adCost) {
        this.adCost = adCost;
    }

    public BigDecimal getChCost() {
        return chCost;
    }

    public void setChCost(BigDecimal chCost) {
        this.chCost = chCost;
    }

    public BigDecimal getInCost() {
        return inCost;
    }

    public void setInCost(BigDecimal inCost) {
        this.inCost = inCost;
    }

    public BigDecimal getAdPrice() {
        return adPrice;
    }

    public void setAdPrice(BigDecimal adPrice) {
        this.adPrice = adPrice;
    }

    public BigDecimal getChPrice() {
        return chPrice;
    }

    public void setChPrice(BigDecimal chPrice) {
        this.chPrice = chPrice;
    }

    public BigDecimal getInPrice() {
        return inPrice;
    }

    public void setInPrice(BigDecimal inPrice) {
        this.inPrice = inPrice;
    }

}


