package com.smi.travel.datalayer.entity;
// Generated Dec 24, 2014 10:24:56 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Passenger generated by hbm2java
 */
public class Passenger {


     private String id;
     private Customer customer;
     private Master master;
     private int orderNo;
     private int isLeader;
     private Set billables = new HashSet(0);

    public Passenger() {
    }

	
    public Passenger(Customer customer, Master master, int orderNo, int isLeader) {
        this.customer = customer;
        this.master = master;
        this.orderNo = orderNo;
        this.isLeader = isLeader;
    }
    public Passenger(Customer customer, Master master, int orderNo, int isLeader, Set billables) {
       this.customer = customer;
       this.master = master;
       this.orderNo = orderNo;
       this.isLeader = isLeader;
       this.billables = billables;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Master getMaster() {
        return this.master;
    }
    
    public void setMaster(Master master) {
        this.master = master;
    }
    public int getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(int orderNo) {
        this.orderNo = orderNo;
    }
    public int getIsLeader() {
        return this.isLeader;
    }
    
    public void setIsLeader(int isLeader) {
        this.isLeader = isLeader;
    }
    public Set getBillables() {
        return this.billables;
    }
    
    public void setBillables(Set billables) {
        this.billables = billables;
    }

}


