package com.smi.travel.datalayer.entity;
// Generated Jul 7, 2015 10:08:38 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

/**
 * PaymentWendy generated by hbm2java
 */
public class PaymentWendy   {


     private String id;
     private MPaymentDoctype MPaymentDoctype;
     private MAccpay MAccpay;
     public  TourOperationDesc tourOperationDesc;
     private MItemstatus MItemstatus;
     private String payNo;
     private Date payDate;
     private Integer account;
     private String invoiceSup;
     private String apCode;
     private String detail;
     private String remark;
     private String chqNo;
     private BigDecimal cash;
     private BigDecimal chqAmount;
     private String createBy;
     private Date createDate;
     private Integer isExport;
     private String currency;
     private List paymentDetailWendies = new LinkedList<PaymentDetailWendy>();

    public PaymentWendy() {
    }


    public PaymentWendy( MPaymentDoctype MPaymentDoctype, MAccpay MAccpay, MItemstatus MItemstatus, String payNo, Date payDate, Integer account, String invoiceSup, String apCode, String detail, String remark, String chqNo, BigDecimal cash, BigDecimal chqAmount, String createBy, Date createDate, List paymentDetailWendies,Integer isExport,String currency,TourOperationDesc tourOperationDesc) {
       this.MPaymentDoctype = MPaymentDoctype;
       this.MAccpay = MAccpay;
       this.MItemstatus = MItemstatus;
       this.payNo = payNo;
       this.payDate = payDate;
       this.account = account;
       this.invoiceSup = invoiceSup;
       this.apCode = apCode;
       this.detail = detail;
       this.remark = remark;
       this.chqNo = chqNo;
       this.cash = cash;
       this.chqAmount = chqAmount;
       this.createBy = createBy;
       this.createDate = createDate;
       this.paymentDetailWendies = paymentDetailWendies;
       this.isExport =isExport;
       this.currency = currency;
       this.tourOperationDesc =  tourOperationDesc;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public MPaymentDoctype getMPaymentDoctype() {
        return this.MPaymentDoctype;
    }
    
    public void setMPaymentDoctype(MPaymentDoctype MPaymentDoctype) {
        this.MPaymentDoctype = MPaymentDoctype;
    }
    public MAccpay getMAccpay() {
        return this.MAccpay;
    }

    public TourOperationDesc getTourOperationDesc() {
        return tourOperationDesc;
    }

    public void setTourOperationDesc(TourOperationDesc tourOperationDesc) {
        this.tourOperationDesc = tourOperationDesc;
    }
    
    public void setMAccpay(MAccpay MAccpay) {
        this.MAccpay = MAccpay;
    }
    public MItemstatus getMItemstatus() {
        return this.MItemstatus;
    }
    
    public void setMItemstatus(MItemstatus MItemstatus) {
        this.MItemstatus = MItemstatus;
    }
    public String getPayNo() {
        return this.payNo;
    }
    
    public void setPayNo(String payNo) {
        this.payNo = payNo;
    }
    public Date getPayDate() {
        return this.payDate;
    }
    
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }
    public Integer getAccount() {
        return this.account;
    }
    
    public void setAccount(Integer account) {
        this.account = account;
    }
    public String getInvoiceSup() {
        return this.invoiceSup;
    }
    
    public void setInvoiceSup(String invoiceSup) {
        this.invoiceSup = invoiceSup;
    }
    public String getApCode() {
        return this.apCode;
    }
    
    public void setApCode(String apCode) {
        this.apCode = apCode;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
 
    public String getChqNo() {
        return this.chqNo;
    }
    
    public void setChqNo(String chqNo) {
        this.chqNo = chqNo;
    }
    public BigDecimal getCash() {
        return this.cash;
    }
    
    public void setCash(BigDecimal cash) {
        this.cash = cash;
    }
    public BigDecimal getChqAmount() {
        return this.chqAmount;
    }
    
    public void setChqAmount(BigDecimal chqAmount) {
        this.chqAmount = chqAmount;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public List getPaymentDetailWendies() {
        return this.paymentDetailWendies;
    }
    
    public void setPaymentDetailWendies(List paymentDetailWendies) {
        this.paymentDetailWendies = paymentDetailWendies;
    }

    public Integer getIsExport() {
        return isExport;
    }

    public void setIsExport(Integer isExport) {
        this.isExport = isExport;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }




}


