package com.smi.travel.datalayer.entity;
// Generated Nov 11, 2015 9:44:58 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * PaymentAirDebit generated by hbm2java
 */
public class PaymentAirDebit  {


     private String id;
     private PaymentAirticket paymentAirticket;
     private String debitNote;
     private BigDecimal debitAmount;

    public PaymentAirDebit() {
    }

    public PaymentAirDebit(PaymentAirticket paymentAirticket, String debitNote, BigDecimal debitAmount) {
       this.paymentAirticket = paymentAirticket;
       this.debitNote = debitNote;
       this.debitAmount = debitAmount;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public PaymentAirticket getPaymentAirticket() {
        return this.paymentAirticket;
    }
    
    public void setPaymentAirticket(PaymentAirticket paymentAirticket) {
        this.paymentAirticket = paymentAirticket;
    }
    public String getDebitNote() {
        return this.debitNote;
    }
    
    public void setDebitNote(String debitNote) {
        this.debitNote = debitNote;
    }
    public BigDecimal getDebitAmount() {
        return this.debitAmount;
    }
    
    public void setDebitAmount(BigDecimal debitAmount) {
        this.debitAmount = debitAmount;
    }




}


