package com.smi.travel.datalayer.entity;
// Generated Jul 9, 2015 9:38:50 AM by Hibernate Tools 4.3.1



/**
 * PaymentAirticketRefund generated by hbm2java
 */
public class PaymentAirticketRefund {


     private String id;
     private PaymentAirticket paymentAirticket;
     private RefundAirticketDetail refundAirticketDetail;

    public PaymentAirticketRefund() {
    }

    public PaymentAirticketRefund(PaymentAirticket paymentAirticket, RefundAirticketDetail refundAirticketDetail) {
       this.paymentAirticket = paymentAirticket;
       this.refundAirticketDetail = refundAirticketDetail;
    }
   
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public PaymentAirticket getPaymentAirticket() {
        return this.paymentAirticket;
    }
    
    public void setPaymentAirticket(PaymentAirticket paymentAirticket) {
        this.paymentAirticket = paymentAirticket;
    }
    public RefundAirticketDetail getRefundAirticketDetail() {
        return this.refundAirticketDetail;
    }
    
    public void setRefundAirticketDetail(RefundAirticketDetail refundAirticketDetail) {
        this.refundAirticketDetail = refundAirticketDetail;
    }

}


