package com.smi.travel.datalayer.entity;
// Generated Nov 19, 2015 9:34:00 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;

/**
 * PaymentOutbound generated by hbm2java
 */
public class PaymentOutbound {
     private String id;
     private MItemstatus MItemstatus;
     private String payNo;
     private Date payDate;
     private Integer account;
     private String invoiceSup;
     private String apCode;
     private String detail;
     private String createBy;
     private Date createDate;
     private Date updateDate;
     private List paymentOutboundDetails = new LinkedList<PaymentOutboundDetail>();

    public PaymentOutbound() {
    }

    public PaymentOutbound(String id, MItemstatus MItemstatus, String payNo, Date payDate, Integer account, String invoiceSup, String apCode, String detail, String createBy, Date createDate, Date updateDate) {
       this.id = id;
       this.MItemstatus = MItemstatus;
       this.payNo = payNo;
       this.payDate = payDate;
       this.account = account;
       this.invoiceSup = invoiceSup;
       this.apCode = apCode;
       this.detail = detail;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateDate = updateDate;
    }
   
    public MItemstatus getMItemstatus() {
        return this.MItemstatus;
    }
    
    public void setMItemstatus(MItemstatus MItemstatus) {
        this.MItemstatus = MItemstatus;
    }
    public String getPayNo() {
        return this.payNo;
    }
    
    public void setPayNo(String payNo) {
        this.payNo = payNo;
    }
    public Date getPayDate() {
        return this.payDate;
    }
    
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }
    public Integer getAccount() {
        return this.account;
    }
    
    public void setAccount(Integer account) {
        this.account = account;
    }
    public String getInvoiceSup() {
        return this.invoiceSup;
    }
    
    public void setInvoiceSup(String invoiceSup) {
        this.invoiceSup = invoiceSup;
    }
    public String getApCode() {
        return this.apCode;
    }
    
    public void setApCode(String apCode) {
        this.apCode = apCode;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public List getPaymentOutboundDetails() {
        return paymentOutboundDetails;
    }

    public void setPaymentOutboundDetails(List paymentOutboundDetails) {
        this.paymentOutboundDetails = paymentOutboundDetails;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

}


