package com.smi.travel.datalayer.entity;
// Generated Jul 9, 2015 9:38:50 AM by Hibernate Tools 4.3.1



/**
 * PaymentAirticketFare generated by hbm2java
 */
public class PaymentAirticketFare {


     private String id;
     private PaymentAirticket paymentAirticket;
     private TicketFareAirline ticketFareAirline;

    public PaymentAirticketFare() {
        this.paymentAirticket = new PaymentAirticket();
    }

    public PaymentAirticketFare(PaymentAirticket paymentAirticket, TicketFareAirline ticketFareAirline) {
       this.paymentAirticket = paymentAirticket;
       this.ticketFareAirline = ticketFareAirline;
    }
   
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public PaymentAirticket getPaymentAirticket() {
        return this.paymentAirticket;
    }
    
    public void setPaymentAirticket(PaymentAirticket paymentAirticket) {
        this.paymentAirticket = paymentAirticket;
    }
    public TicketFareAirline getTicketFareAirline() {
        return this.ticketFareAirline;
    }
    
    public void setTicketFareAirline(TicketFareAirline ticketFareAirline) {
        this.ticketFareAirline = ticketFareAirline;
    }

}


