package com.smi.travel.datalayer.entity;
// Generated Nov 19, 2015 9:34:00 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * PaymentOutboundDetail generated by hbm2java
 */
public class PaymentOutboundDetail {
     private String id;
     private Master master;
     private PaymentOutbound paymentOutbound;
     private PaymentStock paymentStock;
     private MPaytype MPaytype;
     private Integer bookDetailId;
     private String description;
     private String invoiceCreditor;
     private BigDecimal cost;
     private BigDecimal gross;
     private BigDecimal vat;
     private Integer isVat;
     private BigDecimal amount;
     private String currency;
     private BigDecimal recCom;
     private BigDecimal value;
     private String accCode;
     private String bookDetailType;
     private Date exportDate;
     private Integer isExport;
     private Date invoiceDate;
     private Integer isVatRecCom;
     private BigDecimal vatRecCom;
     private BigDecimal wht;
     private BigDecimal payExRate;
     private BigDecimal realExRate;
     private BigDecimal saleAmount;
     private BigDecimal vatRecComAmount;
     private BigDecimal whtAmount;
     private Integer isWht;
     private String saleCurrency;

    public PaymentOutboundDetail() {
    }

    public PaymentOutboundDetail(String id, Master master, PaymentOutbound paymentOutbound, MPaytype MPaytype, Integer bookDetailId, String description, String invoiceCreditor, BigDecimal cost, BigDecimal gross, BigDecimal vat, Integer isVat, BigDecimal amount, String currency, BigDecimal recCom, BigDecimal value, String accCode, String bookDetailType, Integer payStockId, Date exportDate, Integer isExport) {
       this.id = id;
       this.master = master;
       this.paymentOutbound = paymentOutbound;
       this.MPaytype = MPaytype;
       this.bookDetailId = bookDetailId;
       this.description = description;
       this.invoiceCreditor = invoiceCreditor;
       this.cost = cost;
       this.gross = gross;
       this.vat = vat;
       this.isVat = isVat;
       this.amount = amount;
       this.currency = currency;
       this.recCom = recCom;
       this.value = value;
       this.accCode = accCode;
       this.bookDetailType = bookDetailType;
       this.exportDate = exportDate;
       this.isExport =isExport;
    }
     
    public Master getMaster() {
        return this.master;
    }
    
    public void setMaster(Master master) {
        this.master = master;
    }
    public PaymentOutbound getPaymentOutbound() {
        return this.paymentOutbound;
    }
    
    public void setPaymentOutbound(PaymentOutbound paymentOutbound) {
        this.paymentOutbound = paymentOutbound;
    }
    public MPaytype getMPaytype() {
        return this.MPaytype;
    }
    
    public void setMPaytype(MPaytype MPaytype) {
        this.MPaytype = MPaytype;
    }
    public Integer getBookDetailId() {
        return this.bookDetailId;
    }
    
    public void setBookDetailId(Integer bookDetailId) {
        this.bookDetailId = bookDetailId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getInvoiceCreditor() {
        return this.invoiceCreditor;
    }
    
    public void setInvoiceCreditor(String invoiceCreditor) {
        this.invoiceCreditor = invoiceCreditor;
    }
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
    public BigDecimal getGross() {
        return this.gross;
    }
    
    public void setGross(BigDecimal gross) {
        this.gross = gross;
    }
    public BigDecimal getVat() {
        return this.vat;
    }
    
    public void setVat(BigDecimal vat) {
        this.vat = vat;
    }
    public Integer getIsVat() {
        return this.isVat;
    }
    
    public void setIsVat(Integer isVat) {
        this.isVat = isVat;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public BigDecimal getRecCom() {
        return this.recCom;
    }
    
    public void setRecCom(BigDecimal recCom) {
        this.recCom = recCom;
    }
    public BigDecimal getValue() {
        return this.value;
    }
    
    public void setValue(BigDecimal value) {
        this.value = value;
    }
    public String getAccCode() {
        return this.accCode;
    }
    
    public void setAccCode(String accCode) {
        this.accCode = accCode;
    }
    
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getBookDetailType() {
        return bookDetailType;
    }

    public void setBookDetailType(String bookDetailType) {
        this.bookDetailType = bookDetailType;
    }

    public Date getExportDate() {
        return exportDate;
    }

    public void setExportDate(Date exportDate) {
        this.exportDate = exportDate;
    }

    public Integer getIsExport() {
        return isExport;
    }

    public void setIsExport(Integer isExport) {
        this.isExport = isExport;
    }

    public Date getInvoiceDate() {
        return invoiceDate;
    }

    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    public Integer getIsVatRecCom() {
        return isVatRecCom;
    }

    public void setIsVatRecCom(Integer isVatRecCom) {
        this.isVatRecCom = isVatRecCom;
    }

    public BigDecimal getVatRecCom() {
        return vatRecCom;
    }

    public void setVatRecCom(BigDecimal vatRecCom) {
        this.vatRecCom = vatRecCom;
    }

    public BigDecimal getWht() {
        return wht;
    }

    public void setWht(BigDecimal wht) {
        this.wht = wht;
    }

    public BigDecimal getPayExRate() {
        return payExRate;
    }

    public void setPayExRate(BigDecimal payExRate) {
        this.payExRate = payExRate;
    }

    public BigDecimal getRealExRate() {
        return realExRate;
    }

    public void setRealExRate(BigDecimal realExRate) {
        this.realExRate = realExRate;
    }

    public BigDecimal getSaleAmount() {
        return saleAmount;
    }

    public void setSaleAmount(BigDecimal saleAmount) {
        this.saleAmount = saleAmount;
    }

    public BigDecimal getVatRecComAmount() {
        return vatRecComAmount;
    }

    public void setVatRecComAmount(BigDecimal vatRecComAmount) {
        this.vatRecComAmount = vatRecComAmount;
    }

    public BigDecimal getWhtAmount() {
        return whtAmount;
    }

    public void setWhtAmount(BigDecimal whtAmount) {
        this.whtAmount = whtAmount;
    }

    public Integer getIsWht() {
        return isWht;
    }

    public void setIsWht(Integer isWht) {
        this.isWht = isWht;
    }

    public String getSaleCurrency() {
        return saleCurrency;
    }

    public void setSaleCurrency(String saleCurrency) {
        this.saleCurrency = saleCurrency;
    }

    public PaymentStock getPaymentStock() {
        return paymentStock;
    }

    public void setPaymentStock(PaymentStock paymentStock) {
        this.paymentStock = paymentStock;
    }

}


