package com.smi.travel.datalayer.entity;
// Generated Sep 7, 2015 5:55:35 PM by Hibernate Tools 4.3.1


import com.smi.travel.datalayer.entity.PaymentAirticket;
import java.math.BigDecimal;

/**
 * PaymentAirCredit generated by hbm2java
 */
public class PaymentAirCredit {


     private String id;
     private PaymentAirticket paymentAirticket;
     private String creditNote;
     private BigDecimal creditAmount;

    public PaymentAirCredit() {
    }

    public PaymentAirCredit(PaymentAirticket paymentAirticket, String creditNote, BigDecimal creditAmount) {
       this.paymentAirticket = paymentAirticket;
       this.creditNote = creditNote;
       this.creditAmount = creditAmount;
    }
   
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public PaymentAirticket getPaymentAirticket() {
        return this.paymentAirticket;
    }
    
    public void setPaymentAirticket(PaymentAirticket paymentAirticket) {
        this.paymentAirticket = paymentAirticket;
    }
    public String getCreditNote() {
        return this.creditNote;
    }
    
    public void setCreditNote(String creditNote) {
        this.creditNote = creditNote;
    }
    public BigDecimal getCreditAmount() {
        return this.creditAmount;
    }
    
    public void setCreditAmount(BigDecimal creditAmount) {
        this.creditAmount = creditAmount;
    }






}


