package com.smi.travel.datalayer.entity;
// Generated Jan 9, 2015 5:42:39 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * ProductDetail generated by hbm2java
 */
public class ProductDetail   {

     private String id;
     private Product product;
     private Date effectiveFrom;
     private Date effectiveTo;
     private BigDecimal adCost;
     private BigDecimal chCost;
     private BigDecimal inCost;
     private BigDecimal adPrice;
     private BigDecimal chPrice;
     private BigDecimal inPrice;
     private String updateBy;
     private Date updateDate;
     private String createBy;
     private Date createDate;

    public ProductDetail() {
    }

	
    public ProductDetail(Product product, Date effectiveFrom, Date effectiveTo) {
        this.product = product;
        this.effectiveFrom = effectiveFrom;
        this.effectiveTo = effectiveTo;
    }
    public ProductDetail(Product product, Date effectiveFrom, Date effectiveTo, BigDecimal adCost, BigDecimal chCost, BigDecimal inCost, BigDecimal adPrice, BigDecimal chPrice, BigDecimal inPrice , String updateBy, Date updateDate, String createBy, Date createDate) {
       this.product = product;
       this.effectiveFrom = effectiveFrom;
       this.effectiveTo = effectiveTo;
       this.adCost = adCost;
       this.chCost = chCost;
       this.inCost = inCost;
       this.adPrice = adPrice;
       this.chPrice = chPrice;
       this.inPrice = inPrice;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.createBy = createBy;
       this.createDate = createDate;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Date getEffectiveFrom() {
        return this.effectiveFrom;
    }
    
    public void setEffectiveFrom(Date effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }
    public Date getEffectiveTo() {
        return this.effectiveTo;
    }
    
    public void setEffectiveTo(Date effectiveTo) {
        this.effectiveTo = effectiveTo;
    }
    
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public BigDecimal getAdCost() {
        return adCost;
    }

    public void setAdCost(BigDecimal adCost) {
        this.adCost = adCost;
    }

    public BigDecimal getChCost() {
        return chCost;
    }

    public void setChCost(BigDecimal chCost) {
        this.chCost = chCost;
    }

    public BigDecimal getInCost() {
        return inCost;
    }

    public void setInCost(BigDecimal inCost) {
        this.inCost = inCost;
    }

    public BigDecimal getAdPrice() {
        return adPrice;
    }

    public void setAdPrice(BigDecimal adPrice) {
        this.adPrice = adPrice;
    }

    public BigDecimal getChPrice() {
        return chPrice;
    }

    public void setChPrice(BigDecimal chPrice) {
        this.chPrice = chPrice;
    }

    public BigDecimal getInPrice() {
        return inPrice;
    }

    public void setInPrice(BigDecimal inPrice) {
        this.inPrice = inPrice;
    }




}


