package com.smi.travel.datalayer.entity;
// Generated Jan 9, 2015 5:42:39 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product {

     private String id;
     private MProductType MProductType;
     private String code;
     private String name;
     private String description;
     private String remark;
     private Integer isStock;
     private String listItemId;
     private String condition;
     private String include;
     private String instruction;
     private String isUpdate;
     private BigDecimal cost;
     private Set productDetails = new HashSet(0);
     private List productComissions;
     
    public Product() {
    }

	
    public Product(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public Product(MProductType MProductType, String code, String name, String description, String remark, Set productDetails,List productComissions, int isStock) {
       this.MProductType = MProductType;
       this.code = code;
       this.name = name;
       this.description = description;
       this.remark = remark;
       this.isStock = isStock;
       this.productDetails = productDetails;
       this.productComissions = productComissions;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public MProductType getMProductType() {
        return this.MProductType;
    }
    
    public void setMProductType(MProductType MProductType) {
        this.MProductType = MProductType;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Set getProductDetails() {
        return this.productDetails;
    }
    
    public void setProductDetails(Set productDetails) {
        this.productDetails = productDetails;
    }

    public List getProductComissions() {
        return productComissions;
    }

    public void setProductComissions(List productComissions) {
        this.productComissions = productComissions;
    }

    public Integer getIsStock() {
        return isStock;
    }

    public void setIsStock(Integer isStock) {
        this.isStock = isStock;
    }

    public String getListItemId() {
        return listItemId;
    }

    public void setListItemId(String listItemId) {
        this.listItemId = listItemId;
    }

    public String getCondition() {
        return condition;
    }

    public void setCondition(String condition) {
        this.condition = condition;
    }

    public String getInclude() {
        return include;
    }

    public void setInclude(String include) {
        this.include = include;
    }

    public String getInstruction() {
        return instruction;
    }

    public void setInstruction(String instruction) {
        this.instruction = instruction;
    }

    public String getIsUpdate() {
        return isUpdate;
    }

    public void setIsUpdate(String isUpdate) {
        this.isUpdate = isUpdate;
    }

    public BigDecimal getCost() {
        return cost;
    }

    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
}


