package com.smi.travel.datalayer.entity;
// Generated Jan 9, 2015 5:42:39 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ProductDetail generated by hbm2java
 */
public class ProductDetail   {

     private String id;
     private Product product;
     private Date effectiveFrom;
     private Date effectiveTo;
     private Integer adCost;
     private Integer chCost;
     private Integer inCost;
     private Integer adPrice;
     private Integer chPrice;
     private Integer inPrice;
     private String updateBy;
     private Date updateDate;
     private String createBy;
     private Date createDate;

    public ProductDetail() {
    }

	
    public ProductDetail(Product product, Date effectiveFrom, Date effectiveTo) {
        this.product = product;
        this.effectiveFrom = effectiveFrom;
        this.effectiveTo = effectiveTo;
    }
    public ProductDetail(Product product, Date effectiveFrom, Date effectiveTo, Integer adCost, Integer chCost, Integer inCost, Integer adPrice, Integer chPrice, Integer inPrice , String updateBy, Date updateDate, String createBy, Date createDate) {
       this.product = product;
       this.effectiveFrom = effectiveFrom;
       this.effectiveTo = effectiveTo;
       this.adCost = adCost;
       this.chCost = chCost;
       this.inCost = inCost;
       this.adPrice = adPrice;
       this.chPrice = chPrice;
       this.inPrice = inPrice;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.createBy = createBy;
       this.createDate = createDate;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Date getEffectiveFrom() {
        return this.effectiveFrom;
    }
    
    public void setEffectiveFrom(Date effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }
    public Date getEffectiveTo() {
        return this.effectiveTo;
    }
    
    public void setEffectiveTo(Date effectiveTo) {
        this.effectiveTo = effectiveTo;
    }
    public Integer getAdCost() {
        return this.adCost;
    }
    
    public void setAdCost(Integer adCost) {
        this.adCost = adCost;
    }
    public Integer getChCost() {
        return this.chCost;
    }
    
    public void setChCost(Integer chCost) {
        this.chCost = chCost;
    }
    public Integer getInCost() {
        return this.inCost;
    }
    
    public void setInCost(Integer inCost) {
        this.inCost = inCost;
    }
    public Integer getAdPrice() {
        return this.adPrice;
    }
    
    public void setAdPrice(Integer adPrice) {
        this.adPrice = adPrice;
    }
    public Integer getChPrice() {
        return this.chPrice;
    }
    
    public void setChPrice(Integer chPrice) {
        this.chPrice = chPrice;
    }
    public Integer getInPrice() {
        return this.inPrice;
    }
    
    public void setInPrice(Integer inPrice) {
        this.inPrice = inPrice;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


