package com.smi.travel.datalayer.entity;
// Generated Mar 18, 2015 10:03:25 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ProductComission generated by hbm2java
 */
public class ProductComission   {

     private String id;
     private Product productId;
     private Date effectiveFrom;
     private Date effectiveTo;
     private Double comission;
     private Double comissionPercent;
     private String createBy;
     private Date createDate;
     private String updateBy;
     private Date updateDate;

    public ProductComission() {
    }

	
    public ProductComission(Product productId) {
        this.productId = productId;
    }
    public ProductComission(Product productId, Date effectiveFrom, Date effectiveTo, Double comission, String createBy, Date createDate, String updateBy, Date updateDate,Double comissionPercent) {
       this.productId = productId;
       this.effectiveFrom = effectiveFrom;
       this.effectiveTo = effectiveTo;
       this.comission = comission;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.comissionPercent = comissionPercent;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Product getProductId() {
        return this.productId;
    }
    
    public void setProductId(Product productId) {
        this.productId = productId;
    }
    public Date getEffectiveFrom() {
        return this.effectiveFrom;
    }
    
    public void setEffectiveFrom(Date effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }
    public Date getEffectiveTo() {
        return this.effectiveTo;
    }
    
    public void setEffectiveTo(Date effectiveTo) {
        this.effectiveTo = effectiveTo;
    }
    public Double getComission() {
        return this.comission;
    }
    
    public void setComission(Double comission) {
        this.comission = comission;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public Double getComissionPercent() {
        return comissionPercent;
    }

    public void setComissionPercent(Double comissionPercent) {
        this.comissionPercent = comissionPercent;
    }




}


