package com.smi.travel.datalayer.entity;
// Generated Jul 20, 2015 5:52:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ReceiptDetail generated by hbm2java
 */
public class ReceiptDetail {


     private String id;
     private Receipt receipt;
     private String description;
     private String valueType;
     private BigDecimal cost;
     private BigDecimal amount;
     private BigDecimal vat;
     private String remark;

    public ReceiptDetail() {
    }

    public ReceiptDetail(Receipt receipt, String description, String valueType, BigDecimal cost, BigDecimal amount, BigDecimal vat, String remark) {
       this.receipt = receipt;
       this.description = description;
       this.valueType = valueType;
       this.cost = cost;
       this.amount = amount;
       this.vat = vat;
       this.remark = remark;
    }
   
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public Receipt getReceipt() {
        return this.receipt;
    }
    
    public void setReceipt(Receipt receipt) {
        this.receipt = receipt;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getValueType() {
        return this.valueType;
    }
    
    public void setValueType(String valueType) {
        this.valueType = valueType;
    }
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public BigDecimal getVat() {
        return this.vat;
    }
    
    public void setVat(BigDecimal vat) {
        this.vat = vat;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


