package com.smi.travel.datalayer.entity;
// Generated Jul 20, 2015 5:52:41 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ReceiptCredit generated by hbm2java
 */
public class ReceiptCredit {


     private String id;
     private MCreditBank MCreditBank;
     private Receipt receipt;
     private String creditNo;
     private Date creditExpire;
     private Long creditAmount;

    public ReceiptCredit() {
    }

    public ReceiptCredit(MCreditBank MCreditBank, Receipt receipt, String creditNo, Date creditExpire, Long creditAmount) {
       this.MCreditBank = MCreditBank;
       this.receipt = receipt;
       this.creditNo = creditNo;
       this.creditExpire = creditExpire;
       this.creditAmount = creditAmount;
    }
   
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public MCreditBank getMCreditBank() {
        return this.MCreditBank;
    }
    
    public void setMCreditBank(MCreditBank MCreditBank) {
        this.MCreditBank = MCreditBank;
    }
    public Receipt getReceipt() {
        return this.receipt;
    }
    
    public void setReceipt(Receipt receipt) {
        this.receipt = receipt;
    }
    public String getCreditNo() {
        return this.creditNo;
    }
    
    public void setCreditNo(String creditNo) {
        this.creditNo = creditNo;
    }
    public Date getCreditExpire() {
        return this.creditExpire;
    }
    
    public void setCreditExpire(Date creditExpire) {
        this.creditExpire = creditExpire;
    }
    public Long getCreditAmount() {
        return this.creditAmount;
    }
    
    public void setCreditAmount(Long creditAmount) {
        this.creditAmount = creditAmount;
    }




}


