package com.smi.travel.datalayer.entity;
// Generated Jul 20, 2015 5:52:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ReceiptDetail generated by hbm2java
 */
public class ReceiptDetail {


     private String id;
     private PaymentAirticket paymentAirticket;
     private Receipt receipt;
     private InvoiceDetail invoiceDetail;
     private MBilltype MBilltype;
     private PaymentDetailWendy paymentDetailWendy;
     private String description;
     private String displayDescription;
     private BigDecimal cost;
     private String curCost;
     private Integer isVat;
     private BigDecimal vat;
     private BigDecimal amount;
     private String curAmount;
     private String airlineCode;
     private String remark;
     private String invoiceId;
     private String invoiceNo;
     private String invoiceType;
     
    public ReceiptDetail() {
    }

    public ReceiptDetail(PaymentAirticket paymentAirticket, Receipt receipt, InvoiceDetail invoiceDetail, MBilltype MBilltype, String description, String displayDescription, BigDecimal cost, String curCost, Integer isVat, BigDecimal vat, BigDecimal amount, String curAmount, String airlineCode, String remark,PaymentDetailWendy paymentDetailWendy) {
       this.paymentAirticket = paymentAirticket;
       this.receipt = receipt;
       this.invoiceDetail = invoiceDetail;
       this.MBilltype = MBilltype;
       this.description = description;
       this.displayDescription = displayDescription;
       this.cost = cost;
       this.curCost = curCost;
       this.isVat = isVat;
       this.vat = vat;
       this.amount = amount;
       this.curAmount = curAmount;
       this.airlineCode = airlineCode;
       this.remark = remark;
       this.paymentDetailWendy = paymentDetailWendy;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public PaymentAirticket getPaymentAirticket() {
        return this.paymentAirticket;
    }
    
    public void setPaymentAirticket(PaymentAirticket paymentAirticket) {
        this.paymentAirticket = paymentAirticket;
    }
    public Receipt getReceipt() {
        return this.receipt;
    }
    
    public void setReceipt(Receipt receipt) {
        this.receipt = receipt;
    }
    public InvoiceDetail getInvoiceDetail() {
        return this.invoiceDetail;
    }
    
    public void setInvoiceDetail(InvoiceDetail invoiceDetail) {
        this.invoiceDetail = invoiceDetail;
    }
    public MBilltype getMBilltype() {
        return this.MBilltype;
    }
    
    public void setMBilltype(MBilltype MBilltype) {
        this.MBilltype = MBilltype;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDisplayDescription() {
        return this.displayDescription;
    }
    
    public void setDisplayDescription(String displayDescription) {
        this.displayDescription = displayDescription;
    }
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
    public String getCurCost() {
        return this.curCost;
    }
    
    public void setCurCost(String curCost) {
        this.curCost = curCost;
    }
    public Integer getIsVat() {
        return this.isVat;
    }
    
    public void setIsVat(Integer isVat) {
        this.isVat = isVat;
    }
    public BigDecimal getVat() {
        return this.vat;
    }
    
    public void setVat(BigDecimal vat) {
        this.vat = vat;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public String getCurAmount() {
        return this.curAmount;
    }
    
    public void setCurAmount(String curAmount) {
        this.curAmount = curAmount;
    }
    public String getAirlineCode() {
        return this.airlineCode;
    }
    
    public void setAirlineCode(String airlineCode) {
        this.airlineCode = airlineCode;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getInvoiceId() {
        return invoiceId;
    }

    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId;
    }

    public String getInvoiceNo() {
        return invoiceNo;
    }

    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    public String getInvoiceType() {
        return invoiceType;
    }

    public void setInvoiceType(String invoiceType) {
        this.invoiceType = invoiceType;
    }

    public PaymentDetailWendy getPaymentDetailWendy() {
        return paymentDetailWendy;
    }

    public void setPaymentDetailWendy(PaymentDetailWendy paymentDetailWendy) {
        this.paymentDetailWendy = paymentDetailWendy;
    }




}


