package com.smi.travel.datalayer.entity;
// Generated Jul 9, 2015 9:38:50 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;


/**
 * RefundAirticketDetail generated by hbm2java
 */
public class RefundAirticketDetail {


     private String id;
     private RefundAirticket refundAirticket;
     private AirticketPassenger airticketPassenger;
     private String sectorRefund;
     private BigDecimal receiveAirline;
     private BigDecimal payCustomer;
     private BigDecimal agentComission;
     private BigDecimal airComission;
     private BigDecimal profit;
     private Date receiveDate;
     private Date expenseDate;
     private Integer refundCharge;
     private String ticketNo;
     
     private List paymentAirticketRefunds = new LinkedList<PaymentAirticketRefund>();
     private Map<String, Object> ticketFareAirline;

    public RefundAirticketDetail() {
    }

    public RefundAirticketDetail(RefundAirticket refundAirticket,AirticketPassenger airticketPassenger, String sectorRefund, BigDecimal receiveAirline, BigDecimal payCustomer, BigDecimal agentComission,BigDecimal airComission,BigDecimal profit,Date expenseDate,Date receiveDate, List paymentAirticketRefunds) {
       this.refundAirticket = refundAirticket;
       this.airticketPassenger = airticketPassenger;
       this.sectorRefund = sectorRefund;
       this.receiveAirline = receiveAirline;
       this.payCustomer = payCustomer;
       this.agentComission = agentComission;
       this.airComission = airComission;
       this.receiveDate = receiveDate;
       this.profit = profit;
       this.expenseDate = expenseDate;
       this.paymentAirticketRefunds = paymentAirticketRefunds;
    }
   
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    public RefundAirticket getRefundAirticket() {
        return this.refundAirticket;
    }
    
    public void setRefundAirticket(RefundAirticket refundAirticket) {
        this.refundAirticket = refundAirticket;
    }

    public AirticketPassenger getAirticketPassenger() {
        return airticketPassenger;
    }

    public void setAirticketPassenger(AirticketPassenger airticketPassenger) {
        this.airticketPassenger = airticketPassenger;
    }
    
    
    
    public String getSectorRefund() {
        return this.sectorRefund;
    }
    
    public void setSectorRefund(String sectorRefund) {
        this.sectorRefund = sectorRefund;
    }

    public BigDecimal getReceiveAirline() {
        return receiveAirline;
    }

    public void setReceiveAirline(BigDecimal receiveAirline) {
        this.receiveAirline = receiveAirline;
    }

    public BigDecimal getPayCustomer() {
        return payCustomer;
    }

    public void setPayCustomer(BigDecimal payCustomer) {
        this.payCustomer = payCustomer;
    }

    public BigDecimal getAgentComission() {
        return agentComission;
    }

    public void setAgentComission(BigDecimal agentComission) {
        this.agentComission = agentComission;
    }

    public BigDecimal getAirComission() {
        return airComission;
    }

    public void setAirComission(BigDecimal airComission) {
        this.airComission = airComission;
    }

    public Date getReceiveDate() {
        return receiveDate;
    }

    public void setReceiveDate(Date receiveDate) {
        this.receiveDate = receiveDate;
    }

    

    public BigDecimal getProfit() {
        return profit;
    }

    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

    public Date getExpenseDate() {
        return expenseDate;
    }

    public void setExpenseDate(Date expenseDate) {
        this.expenseDate = expenseDate;
    }


    public List getPaymentAirticketRefunds() {
        return paymentAirticketRefunds;
    }

    public void setPaymentAirticketRefunds(List paymentAirticketRefunds) {
        this.paymentAirticketRefunds = paymentAirticketRefunds;
    }

    /**
     * @return the ticketFareAirline
     */
    public Map<String, Object> getTicketFareAirline() {
        return ticketFareAirline;
    }

    /**
     * @param ticketFareAirline the ticketFareAirline to set
     */
    public void setTicketFareAirline(Map<String, Object> ticketFareAirline) {
        this.ticketFareAirline = ticketFareAirline;
    }

    public Integer getRefundCharge() {
        return refundCharge;
    }

    public void setRefundCharge(Integer refundCharge) {
        this.refundCharge = refundCharge;
    }

    public String getTicketNo() {
        return ticketNo;
    }

    public void setTicketNo(String ticketNo) {
        this.ticketNo = ticketNo;
    }

}


