package com.smi.travel.datalayer.entity;
// Generated Jul 7, 2015 11:22:27 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.LinkedList;
import java.util.List;


/**
 * Stock generated by hbm2java
 */
public class Stock {


     private String id;
     private Product product;
     private SystemUser staff;
     private Date effectiveFrom;
     private Date effectiveTo;
     private Date createDate;
     private String description;
     private List stockDetails = new LinkedList<StockDetail>();

    public Stock() {
    }

    public Stock(Product product, SystemUser staff, Date effectiveFrom, Date effectiveTo, Date createDate, String description, List stockDetails) {
       this.product = product;
       this.staff = staff;
       this.effectiveFrom = effectiveFrom;
       this.effectiveTo = effectiveTo;
       this.createDate = createDate;
       this.description = description;
       this.stockDetails = stockDetails;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public SystemUser getStaff() {
        return this.staff;
    }
    
    public void setStaff(SystemUser staff) {
        this.staff = staff;
    }
    public Date getEffectiveFrom() {
        return this.effectiveFrom;
    }
    
    public void setEffectiveFrom(Date effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }
    public Date getEffectiveTo() {
        return this.effectiveTo;
    }
    
    public void setEffectiveTo(Date effectiveTo) {
        this.effectiveTo = effectiveTo;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public List getStockDetails() {
        return this.stockDetails;
    }
    
    public void setStockDetails(List stockDetails) {
        this.stockDetails = stockDetails;
    }




}


