package com.smi.travel.datalayer.entity;
// Generated Jul 9, 2015 9:38:50 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.LinkedList;
import java.util.List;

/**
 * TicketFareAirline generated by hbm2java
 */
public class TicketFareAirline {


     private String id;
     private MAirlineAgent MAirlineAgent;
     private String ticketNo;
     private String ticketType;
     private String ticketBuy;
     private String ticketRounting;
     private String passenger;
     private Date issueDate;
     private Date ticketDate;
     private Long ticketFare;
     private Long ticketTax;
     private Long ticketIns;
     private Long ticketCommission;
     private Long agentCommission;
     private Long salePrice;
     private Integer agentId;
     private String remark;
     private Long overCommission;
     private Long litterCommission;
     private Long decPay;
     private Long addPay;
     private Long agentComPay;
     private Long agentComReceive;
     private Date overDate;
     private Date litterDate;
     private Date decPayDate;
     private Date addPayDate;
     private Date agentPayDate;
     private Date agentReceiveDate;
     private List paymentAirticketFares = new LinkedList<PaymentAirticketFare>();
     private List refundAirticketDetails = new LinkedList<RefundAirticketDetail>();

    public TicketFareAirline() {
    }

    public TicketFareAirline(MAirlineAgent MAirlineAgent, String ticketNo, String ticketType, String ticketBuy, String ticketRounting, String passenger, Date issueDate, Date ticketDate, Long ticketFare, Long ticketTax, Long ticketIns, Long ticketCommission, Long agentCommission, Long salePrice, Integer agentId, String remark, Long overCommission, Long litterCommission, Long decPay, Long addPay, Long agentComPay, Long agentComReceive, Date overDate, Date litterDate, Date decPayDate, Date addPayDate, Date agentPayDate, Date agentReceiveDate, List paymentAirticketFares, List refundAirticketDetails) {
       this.MAirlineAgent = MAirlineAgent;
       this.ticketNo = ticketNo;
       this.ticketType = ticketType;
       this.ticketBuy = ticketBuy;
       this.ticketRounting = ticketRounting;
       this.passenger = passenger;
       this.issueDate = issueDate;
       this.ticketDate = ticketDate;
       this.ticketFare = ticketFare;
       this.ticketTax = ticketTax;
       this.ticketIns = ticketIns;
       this.ticketCommission = ticketCommission;
       this.agentCommission = agentCommission;
       this.salePrice = salePrice;
       this.agentId = agentId;
       this.remark = remark;
       this.overCommission = overCommission;
       this.litterCommission = litterCommission;
       this.decPay = decPay;
       this.addPay = addPay;
       this.agentComPay = agentComPay;
       this.agentComReceive = agentComReceive;
       this.overDate = overDate;
       this.litterDate = litterDate;
       this.decPayDate = decPayDate;
       this.addPayDate = addPayDate;
       this.agentPayDate = agentPayDate;
       this.agentReceiveDate = agentReceiveDate;
       this.paymentAirticketFares = paymentAirticketFares;
       this.refundAirticketDetails = refundAirticketDetails;
    }
   
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public MAirlineAgent getMAirlineAgent() {
        return this.MAirlineAgent;
    }
    
    public void setMAirlineAgent(MAirlineAgent MAirlineAgent) {
        this.MAirlineAgent = MAirlineAgent;
    }
    public String getTicketNo() {
        return this.ticketNo;
    }
    
    public void setTicketNo(String ticketNo) {
        this.ticketNo = ticketNo;
    }
    public String getTicketType() {
        return this.ticketType;
    }
    
    public void setTicketType(String ticketType) {
        this.ticketType = ticketType;
    }
    public String getTicketBuy() {
        return this.ticketBuy;
    }
    
    public void setTicketBuy(String ticketBuy) {
        this.ticketBuy = ticketBuy;
    }
    public String getTicketRounting() {
        return this.ticketRounting;
    }
    
    public void setTicketRounting(String ticketRounting) {
        this.ticketRounting = ticketRounting;
    }
    public String getPassenger() {
        return this.passenger;
    }
    
    public void setPassenger(String passenger) {
        this.passenger = passenger;
    }
    public Date getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }
    public Date getTicketDate() {
        return this.ticketDate;
    }
    
    public void setTicketDate(Date ticketDate) {
        this.ticketDate = ticketDate;
    }
    public Long getTicketFare() {
        return this.ticketFare;
    }
    
    public void setTicketFare(Long ticketFare) {
        this.ticketFare = ticketFare;
    }
    public Long getTicketTax() {
        return this.ticketTax;
    }
    
    public void setTicketTax(Long ticketTax) {
        this.ticketTax = ticketTax;
    }
    public Long getTicketIns() {
        return this.ticketIns;
    }
    
    public void setTicketIns(Long ticketIns) {
        this.ticketIns = ticketIns;
    }
    public Long getTicketCommission() {
        return this.ticketCommission;
    }
    
    public void setTicketCommission(Long ticketCommission) {
        this.ticketCommission = ticketCommission;
    }
    public Long getAgentCommission() {
        return this.agentCommission;
    }
    
    public void setAgentCommission(Long agentCommission) {
        this.agentCommission = agentCommission;
    }
    public Long getSalePrice() {
        return this.salePrice;
    }
    
    public void setSalePrice(Long salePrice) {
        this.salePrice = salePrice;
    }
    public Integer getAgentId() {
        return this.agentId;
    }
    
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Long getOverCommission() {
        return this.overCommission;
    }
    
    public void setOverCommission(Long overCommission) {
        this.overCommission = overCommission;
    }
    public Long getLitterCommission() {
        return this.litterCommission;
    }
    
    public void setLitterCommission(Long litterCommission) {
        this.litterCommission = litterCommission;
    }
    public Long getDecPay() {
        return this.decPay;
    }
    
    public void setDecPay(Long decPay) {
        this.decPay = decPay;
    }
    public Long getAddPay() {
        return this.addPay;
    }
    
    public void setAddPay(Long addPay) {
        this.addPay = addPay;
    }
    public Long getAgentComPay() {
        return this.agentComPay;
    }
    
    public void setAgentComPay(Long agentComPay) {
        this.agentComPay = agentComPay;
    }
    public Long getAgentComReceive() {
        return this.agentComReceive;
    }
    
    public void setAgentComReceive(Long agentComReceive) {
        this.agentComReceive = agentComReceive;
    }
    public Date getOverDate() {
        return this.overDate;
    }
    
    public void setOverDate(Date overDate) {
        this.overDate = overDate;
    }
    public Date getLitterDate() {
        return this.litterDate;
    }
    
    public void setLitterDate(Date litterDate) {
        this.litterDate = litterDate;
    }
    public Date getDecPayDate() {
        return this.decPayDate;
    }
    
    public void setDecPayDate(Date decPayDate) {
        this.decPayDate = decPayDate;
    }
    public Date getAddPayDate() {
        return this.addPayDate;
    }
    
    public void setAddPayDate(Date addPayDate) {
        this.addPayDate = addPayDate;
    }
    public Date getAgentPayDate() {
        return this.agentPayDate;
    }
    
    public void setAgentPayDate(Date agentPayDate) {
        this.agentPayDate = agentPayDate;
    }
    public Date getAgentReceiveDate() {
        return this.agentReceiveDate;
    }
    
    public void setAgentReceiveDate(Date agentReceiveDate) {
        this.agentReceiveDate = agentReceiveDate;
    }

    public List getPaymentAirticketFares() {
        return paymentAirticketFares;
    }

    public void setPaymentAirticketFares(List paymentAirticketFares) {
        this.paymentAirticketFares = paymentAirticketFares;
    }

    public List getRefundAirticketDetails() {
        return refundAirticketDetails;
    }

    public void setRefundAirticketDetails(List refundAirticketDetails) {
        this.refundAirticketDetails = refundAirticketDetails;
    }

}


