package com.smi.travel.datalayer.entity;
// Generated Aug 31, 2015 4:01:52 PM by Hibernate Tools 4.3.1

import com.smi.travel.datalayer.entity.Invoice;
import com.smi.travel.datalayer.entity.TicketFareAirline;




/**
 * TicketFareInvoice generated by hbm2java
 */
public class TicketFareInvoice {


     private String id;
     private Invoice invoice;
     private TicketFareAirline ticketFareAirline;

    public TicketFareInvoice() {
    }

    public TicketFareInvoice(Invoice invoice, TicketFareAirline ticketFareAirline) {
       this.invoice = invoice;
       this.ticketFareAirline = ticketFareAirline;
    }
   
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public TicketFareAirline getTicketFareAirline() {
        return this.ticketFareAirline;
    }
    
    public void setTicketFareAirline(TicketFareAirline ticketFareAirline) {
        this.ticketFareAirline = ticketFareAirline;
    }




}


