package com.smi.travel.datalayer.entity;
// Generated Mar 18, 2015 10:03:25 AM by Hibernate Tools 3.6.0



/**
 * TourOperationBookorder generated by hbm2java
 */
public class TourOperationBookorder  {


     private String id;
     private TourOperationDesc tourOperationDesc;
     private Master master;
     private Integer order;

    public TourOperationBookorder() {
    }

    public TourOperationBookorder(TourOperationDesc tourOperationDesc, Master master, Integer order) {
       this.tourOperationDesc = tourOperationDesc;
       this.master = master;
       this.order = order;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public TourOperationDesc getTourOperationDesc() {
        return this.tourOperationDesc;
    }
    
    public void setTourOperationDesc(TourOperationDesc tourOperationDesc) {
        this.tourOperationDesc = tourOperationDesc;
    }
    public Master getMaster() {
        return this.master;
    }
    
    public void setMaster(Master master) {
        this.master = master;
    }
    public Integer getOrder() {
        return this.order;
    }
    
    public void setOrder(Integer order) {
        this.order = order;
    }




}


