package com.smi.travel.datalayer.entity;
// Generated Mar 18, 2015 10:03:25 AM by Hibernate Tools 3.6.0

import java.math.BigDecimal;




/**
 * TourOperationExpense generated by hbm2java
 */
public class TourOperationExpense {


     private String id;
     private TourOperationDesc tourOperationDesc;
     private String description;
     private Integer qty;
     private BigDecimal amount;
     private String currency;
     private String priceType;

    public TourOperationExpense() {
    }

    public TourOperationExpense(TourOperationDesc tourOperationDesc, String description, Integer qty, BigDecimal amount, String currency, String priceType) {
       this.tourOperationDesc = tourOperationDesc;
       this.description = description;
       this.qty = qty;
       this.amount = amount;
       this.currency = currency;
       this.priceType = priceType;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public TourOperationDesc getTourOperationDesc() {
        return this.tourOperationDesc;
    }
    
    public void setTourOperationDesc(TourOperationDesc tourOperationDesc) {
        this.tourOperationDesc = tourOperationDesc;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public String getPriceType() {
        return this.priceType;
    }
    
    public void setPriceType(String priceType) {
        this.priceType = priceType;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

}


