package com.smi.travel.datalayer.entity;
// Generated Mar 18, 2015 10:03:25 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TourOperationDesc generated by hbm2java
 */
public class TourOperationDesc   {


     private String id;
     private SystemUser staffByGuide2;
     private SystemUser staffByGuide1;
     private Daytour daytour;
     private Date tourDate;
     private String meal;
     private String transferInfo;
     private String remark;
     private Set tourOperationExpenses = new HashSet(0);
     private Set tourOperationDrivers = new HashSet(0);

    public TourOperationDesc() {
    }

	
    public TourOperationDesc(Daytour daytour, Date tourDate) {
        this.daytour = daytour;
        this.tourDate = tourDate;
    }
    public TourOperationDesc(SystemUser staffByGuide2, SystemUser staffByGuide1, Daytour daytour, Date tourDate, String meal, String transferInfo, String remark, Set tourOperationExpenses, Set tourOperationDrivers) {
       this.staffByGuide2 = staffByGuide2;
       this.staffByGuide1 = staffByGuide1;
       this.daytour = daytour;
       this.tourDate = tourDate;
       this.meal = meal;
       this.transferInfo = transferInfo;
       this.remark = remark;
       this.tourOperationExpenses = tourOperationExpenses;
       this.tourOperationDrivers = tourOperationDrivers;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public SystemUser getStaffByGuide2() {
        return this.staffByGuide2;
    }
    
    public void setStaffByGuide2(SystemUser staffByGuide2) {
        this.staffByGuide2 = staffByGuide2;
    }
    public SystemUser getStaffByGuide1() {
        return this.staffByGuide1;
    }
    
    public void setStaffByGuide1(SystemUser staffByGuide1) {
        this.staffByGuide1 = staffByGuide1;
    }
    public Daytour getDaytour() {
        return this.daytour;
    }
    
    public void setDaytour(Daytour daytour) {
        this.daytour = daytour;
    }
    public Date getTourDate() {
        return this.tourDate;
    }
    
    public void setTourDate(Date tourDate) {
        this.tourDate = tourDate;
    }
    public String getMeal() {
        return this.meal;
    }
    
    public void setMeal(String meal) {
        this.meal = meal;
    }
    public String getTransferInfo() {
        return this.transferInfo;
    }
    
    public void setTransferInfo(String transferInfo) {
        this.transferInfo = transferInfo;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Set getTourOperationExpenses() {
        return this.tourOperationExpenses;
    }
    
    public void setTourOperationExpenses(Set tourOperationExpenses) {
        this.tourOperationExpenses = tourOperationExpenses;
    }
    public Set getTourOperationDrivers() {
        return this.tourOperationDrivers;
    }
    
    public void setTourOperationDrivers(Set tourOperationDrivers) {
        this.tourOperationDrivers = tourOperationDrivers;
    }




}


