package com.smi.travel.datalayer.entity;
// Generated Mar 18, 2015 10:03:25 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TransferJob generated by hbm2java
 */
public class TransferJob   {


     private String id;
     private SystemUser staffByDriverId;
     private SystemUser staffByGuildeId;
     private String documentNo;
     private Date transferDate;
     private Date transferTime;
     private String tour;
     private String place;
     private String placeOther;
     private String remark;

    public TransferJob() {
        
    }

	
    public TransferJob(String documentNo, Date transferDate) {
        this.documentNo = documentNo;
        this.transferDate = transferDate;
    }
    public TransferJob(SystemUser staffByDriverId, SystemUser staffByGuildeId, String documentNo, Date transferDate, Date transferTime, String tour, String place,String placeOther, String remark) {
       this.staffByDriverId = staffByDriverId;
       this.staffByGuildeId = staffByGuildeId;
       this.documentNo = documentNo;
       this.transferDate = transferDate;
       this.transferTime = transferTime;
       this.tour = tour;
       this.place = place;
       this.placeOther = placeOther;
       this.remark = remark;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public SystemUser getStaffByDriverId() {
        return this.staffByDriverId;
    }
    
    public void setStaffByDriverId(SystemUser staffByDriverId) {
        this.staffByDriverId = staffByDriverId;
    }
    public SystemUser getStaffByGuildeId() {
        return this.staffByGuildeId;
    }
    
    public void setStaffByGuildeId(SystemUser staffByGuildeId) {
        this.staffByGuildeId = staffByGuildeId;
    }
    public String getDocumentNo() {
        return this.documentNo;
    }
    
    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo;
    }
    public Date getTransferDate() {
        return this.transferDate;
    }
    
    public void setTransferDate(Date transferDate) {
        this.transferDate = transferDate;
    }
    public Date getTransferTime() {
        return this.transferTime;
    }
    
    public void setTransferTime(Date transferTime) {
        this.transferTime = transferTime;
    }
    public String getTour() {
        return this.tour;
    }
    
    public void setTour(String tour) {
        this.tour = tour;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }

    public String getPlaceOther() {
        return placeOther;
    }

    public void setPlaceOther(String placeOther) {
        this.placeOther = placeOther;
    }
    
    
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


